### ISSUE TITLE
Issuer: Email missing

### ISSUE THREAD

**Issue by JuliaKleeberger** [mint-o-badges/badgr-ui#101]
**Name the test case**
Want to create a new issuer

**Describe the bug**
No Email address appears to choose from 

**To Reproduce**
1. Go to 'create new issuer'
2. Select Email-Address 

**Expected behavior**
Selection of email addresses 

**Screenshots**
No Email Address shows up for selection 

**Desktop (please complete the following information; remove if not applicable):**
 - OS: Mac OS 

**Smartphone (please complete the following information; remove if not applicable):**
 - Version [e.g. 2
![Bildschirmfoto 2024-03-25 um 15 46 54](https://github.com/mint-o-badges/badgr-ui/assets/12052169/47cf3adb-5cc6-406c-9b71-ac9293cd0763)
2]

**Additional context**
Add any other context about your observations here.

**Comment by timber-they** [comment]
@JuliaKleeberger Hi Julia, sometimes it takes a bit until a verified E-Mail address is available for creating an issuer. That doesn't mean that this wouldn't be an issue, but it would have a far lower priority. Can you test it again and check, if your E-Mail address is now available?

**Comment by JuliaKleeberger** [comment]
👍🏻
