### ISSUE TITLE
New PDF Layout

### ISSUE THREAD

**Issue by jona159** [mint-o-badges/badgr-ui#120]

**Comment by jona159** [comment]
Implement new PDF Layout based on the proposed wireframes from [asana](https://app.asana.com/0/1205782519509072/1206765520450288)

**Comment by zven** [comment]
I briefly tested the pdf export feature (see attachment). Some elements look odd:
- The OEB-Logo is distorted.
- The instiution logo is distorted and contains a gray box (I think that was supposed to be just a placeholder).
- A long duration breaks the formatting.
- The starburst pattern is very pixelated.

[Dummy-Badge - 02042024.pdf](https://github.com/mint-o-badges/badgr-ui/files/14839327/Dummy-Badge.-.02042024.pdf)
