### ISSUE TITLE
ui: recolor remaining elements with OEB purple

### ISSUE THREAD

**Issue by zven** [mint-o-badges/badgr-ui#130]
Many elements on the website are still colored in the "old" OEB blue/purple but should also be colored in the blue/purple: #492E98 (see #83)

Some examples:
"Badges" text, login-button and arrows are still in the old color.

![Image](https://github.com/mint-o-badges/badgr-ui/assets/2930332/89af3ba5-c191-4d6d-8b93-7156f7aef960)
![Image](https://github.com/mint-o-badges/badgr-ui/assets/2930332/8cb64008-df1d-469f-9623-d11a52458c9d)

**Comment by zven** [comment]
> This occurred as the color wasn't updated in staging env. file. Now purple color should be updated everywhere.

@YouQam Really? There are still those brightly purple elements on the staging website.

**Comment by YouQam** [comment]
> > This occurred as the color wasn't updated in staging env. file. Now purple color should be updated everywhere.
> 
> @YouQam Really? There are still those brightly purple elements on the staging website.

@zven  Can you mention where exactly or add a screenshot here?
