### ISSUE TITLE
Landing page: different button forms/ not functionable

### ISSUE THREAD

**Issue by JuliaKleeberger** [mint-o-badges/badgr-ui#140]
**Name the test case**
Landing page: different button forms / do not work

**Describe the bug**
on the landing page, the red button does not has rounded corners
the whole text on the red button is not in bold / the button link does not work
the whole text on the yellow button is not in bold / the button link does not work

**Expected behavior**
the red button should have round corners (the same as the yellow one on the page) 
the text on the red button should be completely in bold letters: "Jetzt Badges erstellen"
the text on the yellow button should be completely in bold letters: "Jetzt Badges erstellen"
>> the buttons have to link to the following pages: 
- when not logged in: 
- when already logged in: 

**Screenshots**
![image](https://github.com/mint-o-badges/badgr-ui/assets/12052169/2967e639-db86-442c-a951-dc1627be6b7e)

![image](https://github.com/mint-o-badges/badgr-ui/assets/12052169/45111dd8-7f43-47cc-a1ed-1717bc430dd3)

**Desktop (please complete the following information; remove if not applicable):**
 - OS: [e.g. Windows 10, MacOS 14.03, Ubuntu]

**Smartphone (please complete the following information; remove if not applicable):**

**Additional context**
Add any other context about your observations here.

**Comment by schmidfranzi** [comment]
Thank you @zven: Please turn them into buttons with the following functionality:
- When not logged in: To the login window (I will create a separate that adds a link to register within the login field)
- When logged in: To my institutions

**Comment by schmidfranzi** [comment]
@zven agreed :)

**Comment by timber-they** [comment]
The unit tests don't pass yet, so I'm putting this back to Next

**Comment by timber-they** [comment]
Requested changes
