### ISSUE TITLE
Mobile view landing page: Icons of institutions are too small

### ISSUE THREAD

**Issue by schmidfranzi** [mint-o-badges/badgr-ui#144]
**Name the test case**
Landingpage on iOS firefox

**Describe the bug**
On the landingpage in iOS firefox within the section "Diese Institutionen nutzen bereits Open Educational Badges" the Icons of the institutions are way too small. Please make it bigger

**Screenshots**
![Uploading IMG_0510.PNG…]()

**Smartphone (please complete the following information; remove if not applicable):**
 - OS: iOS 
 - Browser firefox

**Comment by zven** [comment]
@schmidfranzi Your uploaded screenshot is missing here as well.

**Comment by schmidfranzi** [comment]
![IMG_0510 3](https://github.com/mint-o-badges/badgr-ui/assets/164329233/9be25138-f8ed-4624-900a-c2d6243a49f2)

Here it is - sorry :)

**Comment by TobiSchumacher** [comment]
I have the same problem, but the logos look different than in Franzi's screenshot. I also used firefox but on Android.

![Screenshot_20240408-100945](https://github.com/mint-o-badges/badgr-ui/assets/164183217/18ec02fe-7801-46b3-986e-839cf657350c)

**Comment by timber-they** [comment]
The unit tests don't pass yet, so I'm putting this back to Next
