### ISSUE TITLE
Button is doubled

### ISSUE THREAD

**Issue by schmidfranzi** [mint-o-badges/badgr-ui#145]
**Name the test case**
Logged in - create institution

**Describe the bug**
when I want to create an institution there is the button for it doulbed. please reduce it to only one button.

**Expected behavior**
only one call to action is there to create a new institution

**Screenshots**
![IMG_0505](https://github.com/mint-o-badges/badgr-ui/assets/164329233/9d3f3a4f-23bf-4fbf-8ca4-68ac75caa7b6)

**Smartphone (please complete the following information; remove if not applicable):**
 - Device: IPhone
 - Browser firefox

**Comment by IngaSchmidt** [comment]
Same for Android, Chrome

**Comment by zven** [comment]
@schmidfranzi and @IngaSchmidt This is actually an effect of the mobile view: On a bigger screen (e.g. Desktop) the lower portion is in the center of the big screen.

**Comment by jona159** [comment]
Outdated
