### ISSUE TITLE
Canceling the Photo Upload kills the whole Badge creating process

### ISSUE THREAD

**Issue by schmidfranzi** [mint-o-badges/badgr-ui#148]
**Name the test case**
Create a Badge

**Describe the bug**
When I create a Badge and I have filled in already some fields: Then I want to add a picture. Therefore I click on the "Drag and Drop oder Datei auswählen..." that opens my finder window on my computer. I don't find the picture I am looking for and therefore I click on cancel. That closes my window- BUT it also kills the Badge creating process and brings me back to the interface where I can see my institution and start the process all over again.  

**To Reproduce**
1. Go to Meine Institution
2. Click on Badge erstellen
3. Scroll down to Drag & Drop then click cancel

**Expected behavior**
After clicking on cancel I want to be back within the badge editing view. All data should still be there. 

**Screenshots**
<img width="1330" alt="Screenshot 2024-04-05 at 09 52 52" src="https://github.com/mint-o-badges/badgr-ui/assets/164329233/ce6c3fc5-d75b-4080-b1d7-552bda8c12e4">

**Desktop (please complete the following information; remove if not applicable):**
 - OS:  MacOS 
 - Browser Chrome

**Smartphone (please complete the following information; remove if not applicable):**
 - Device: IPhone
 - Browser firefox

**Comment by IngaSchmidt** [comment]
In addition: If I create a badge and then edit it again, I always have to select a new icon or a new photo.

OS: Windows 11
Browser: Microsoft Edge

**Comment by timber-they** [comment]
@IngaSchmidt this seems to be an unrelated issue, so please create a separate ticket for it.
