### ISSUE TITLE
"Badge erstellen" is not optimized for mobile view

### ISSUE THREAD

**Issue by schmidfranzi** [mint-o-badges/badgr-ui#149]
**Name the test case**
Badge erstellen

**Describe the bug**
The view is not optimized for the mobile device screen size

**Expected behavior**
The size needs to adapt to the screensize

**Screenshots**
![IMG_0512](https://github.com/mint-o-badges/badgr-ui/assets/164329233/2ad02c9b-5f8d-48c7-844f-57a85c03ce10)

**Smartphone (please complete the following information; remove if not applicable):**
 - Device: iPhone
 - Browser firefox

**Comment by zven** [comment]
We could use this issue to overhaul the badge creation page in general (adapt to mobile screens, unify text entry and styles).

**Comment by schmidfranzi** [comment]
Great, what do you need for it @zven ? @Annicelia wireframes for the mobile view?

**Comment by zven** [comment]
Designs can be found here in "Ideen für Entwicklung": https://www.figma.com/file/rq5IOcBWjVAl7tmvtq0GqS/Use-Cases?type=design&node-id=573-2160&mode=design
Screenshots here: https://app.asana.com/0/1205782519509072/1207055131738155/f

**Comment by YouQam** [comment]
I put it back to next to resolve requested changes.
