### ISSUE TITLE
Fix typos

### ISSUE THREAD

**Issue by IngaSchmidt** [mint-o-badges/badgr-ui#157]
**Name the test case**
Generally

**Describe the bug**
There are a few typos on the landing page.

- "Ich weisss" | delete an “s”
- "ausser-schulisch" | add a “ß”, delete the "-"
- "gGmbh | capitalize “H” > gGmbH

**Screenshots**
![image](https://github.com/mint-o-badges/badgr-ui/assets/164493443/813d2c44-5fa1-4f1d-9423-127a857ff2a5)

![image](https://github.com/mint-o-badges/badgr-ui/assets/164493443/32a9ed90-6f59-4566-950a-13ddfd489024)

![image](https://github.com/mint-o-badges/badgr-ui/assets/164493443/f5251fc7-8e21-4eab-b49b-84a66df0f066)

**Desktop (please complete the following information; remove if not applicable):**

-   OS: Windows 11
-   Browser: Microsoft Edge
-   Version 123.0.2420.65

**Comment by IngaSchmidt** [comment]
In addition: There is also a typo in “Mitglieder bearbetien” | Swap “t” and “i”

![image](https://github.com/mint-o-badges/badgr-ui/assets/164493443/c332ff47-328c-48f2-87fe-34cdbc6ca0af)

**Comment by IngaSchmidt** [comment]
In addition: There ist also a typo when I register | delete "an"

![image](https://github.com/mint-o-badges/badgr-ui/assets/164493443/1e8bd6fe-d46e-4b76-b34f-e3aca0d9c8f3)

**Comment by IngaSchmidt** [comment]
In addition: Capitalize on “Institutionen.”

<img width="592" alt="image" src="https://github.com/mint-o-badges/badgr-ui/assets/164493443/a3271919-7696-4388-b207-83c2d65fb595">

**Comment by timber-they** [comment]
@IngaSchmidt the E-Mail verification "typo" isn't actually a typo; typically the entered E-Mail address should be printed after the "an". Can you create a more detailed description on how to reproduce this and create a separate ticket for it?

**Comment by timber-they** [comment]
Also the last point with differing texts I can't reproduce; I always get the text "Verifiziere deine E-Mail-Adresse". Looking at the code, texts like "Überprüfen Sie Ihre E-Mail-Adresse..." should only appear when the login failed, meaning that the credentials were wrong.

**Comment by IngaSchmidt** [comment]
> @IngaSchmidt the E-Mail verification "typo" isn't actually a typo; typically the entered E-Mail address should be printed after the "an". Can you create a more detailed description on how to reproduce this and create a separate ticket for it?

@timber-they: Hi, unfortunately I can't reproduce this because I'm already registered with my two email addresses. When I registered, I got this message where it only says "an" and no e-mail address. Should I still create a new issue?

**Comment by IngaSchmidt** [comment]
> Also the last point with differing texts I can't reproduce; I always get the text "Verifiziere deine E-Mail-Adresse". Looking at the code, texts like "Überprüfen Sie Ihre E-Mail-Adresse..." should only appear when the login failed, meaning that the credentials were wrong.

@timber-they: When I registered with my smartphone (Android, Chrome), I got this message: 
![Screenshot_20240405_144245_Chrome](https://github.com/mint-o-badges/badgr-ui/assets/164493443/9c7306b9-d8a1-4fe4-87b1-b8920c5349b2)
