### ISSUE TITLE
Create Badge: I can't set a duration

### ISSUE THREAD

**Issue by IngaSchmidt** [mint-o-badges/badgr-ui#159]
**Name the test case**
Create Badge

**Describe the bug**
I can't set a duration or I can't find it

- OS: Windows 11
- Browser: Microsoft Edge
- Version 123.0.2420.65

**Comment by zven** [comment]
When creating a badge there is no way to add a duration. Albeit not setting any duration, there is a one hour default duration in the badge view once the badge was created.

Tasks:

- [ ] add duration to badge creation process
- [ ] only display a duration in the badge view if it's actually set
- [ ] remove the (now obsolete) level information

**Comment by zven** [comment]
@IngaSchmidt We addressed the outdated frames already here: https://github.com/mint-o-badges/badgr-ui/issues/127 They are now available on the staging system.

**Comment by timber-they** [comment]
@zven so should the Duration option be optional, with an empty default value? And what is this option supposed to say? Isn't the thing, that it was supposed to say (minimal study load required) already covered by the duration option of the competencies?
Note that this option existed but was removed with the redesign of the badge creation process. To me the requirements don't seem so clear now.

**Comment by zven** [comment]
Adding a duration (in minutes) should still be possible, albeit optional. If no duration is added, then the field (see Ingas screenshot) should simply be not shown in the created badge.
