### ISSUE TITLE
Create badge: AI-Tool doesn't work

### ISSUE THREAD

**Issue by IngaSchmidt** [mint-o-badges/badgr-ui#160]
**Name the test case**
Create a competency badge

**Describe the bug**
When I enter a course description and click "Passende Kompetenzen vorschlagen" nothing happens. Is the course description possibly too long?

**Screenshots**
<img width="761" alt="image" src="https://github.com/mint-o-badges/badgr-ui/assets/164493443/dc05fa68-15ed-40f9-890f-f89ed909a55a">

**Desktop (please complete the following information; remove if not applicable):**

- OS: Windows 11
- Browser: Microsoft Edge
- Version 123.0.2420.65

**Comment by timber-they** [comment]
It seems we can't handle üöä currently

**Comment by Annicelia** [comment]
doesn't work in MacOS Browser Firefox
![Bildschirmfoto 2024-04-08 um 15 49 02](https://github.com/mint-o-badges/badgr-ui/assets/164371483/b11f7041-51bf-444b-9243-c89a54fdb5a1)

**Comment by timber-they** [comment]
@Annicelia yes, that's what I wanted to confirm with my comment. It's a bug and I already fixed it and as soon as it's through the review, it'll be updated on staging.openbadges.education
