### ISSUE TITLE
Wallet: Download/Upload Badge broken

### ISSUE THREAD

**Issue by Annicelia** [mint-o-badges/badgr-ui#174]
MacOS Browser Firefox

when I receive a badge via email and download it, it is a png. when I try to upload it into the wallet, I get an error notification.
![Bildschirmfoto 2024-04-08 um 17 04 10](https://github.com/mint-o-badges/badgr-ui/assets/164371483/a7882678-9731-4987-a667-b60b9ffade81)
the same applies to JSON

**Comment by timber-they** [comment]
I can't reproduce this if the E-Mail in the badge is one of the verified E-Mail addresses for the recipients account (which should be the default flow). However, the error message does appear if this isn't the case. Can you confirm that you didn't use a verified mail address (@zven @Annicelia)?
If that is indeed the case, in my opinion only the error message needs to be adjusted.

**Comment by zven** [comment]
The process now seems to work for @Annicelia and we can't reproduce the error.

**Comment by zven** [comment]
We couldn't reproduce that error

**Comment by zven** [comment]
@timber-they After also checking the mybadges plattform: This happens indeed only if you try to upload a badge that is not connected to your email address
