### ISSUE TITLE
AI Tool: Results are in English

### ISSUE THREAD

**Issue by Annicelia** [mint-o-badges/badgr-ui#177]
When using the AI Tool, the suitable ESCO skills are shown in English. Can we change this so that they are displayed in German?

MacOS Browser Firefox
![Bildschirmfoto 2024-04-08 um 17 23 04](https://github.com/mint-o-badges/badgr-ui/assets/164371483/3c2c73fa-d436-452c-b065-9f0843455b24)

**Comment by zven** [comment]
@Annicelia Have you added a German or an English text? According to my understanding, we should get a German translation from the UI tool based on the language the description text is written in.

**Comment by Annicelia** [comment]
It was a German text :) I just tried it again with another one, still English results

**Comment by zven** [comment]
The dummy frontend (http://49.12.65.167:3001/ui/, user: `skillnavigator`, pw: `skillnavigator_goes_ai`) does also respond with English texts only. According to the swagger documentation (https://disruptive-elements.com/fileserver/skillnavigator/docs/swagger.json) there is also supposed to be a language tag in the response indicating the language of the analysed text. It is apparently not used. I contacted the developers of the AI tools for clarification.

**Comment by zven** [comment]
Update: They send us English content only since they were working under the assumption that we also have a copy of the esco database that we could use to look up translations etc. We don't have that (yet).

**Comment by Annicelia** [comment]
ok so they can simply change this to sending us German content?

**Comment by zven** [comment]
We now get German or English AI results! :-)

In addition, the AI-tool team also updated the API to return some additional information:

- Skills werden in Deutsch oder Englisch zurückgegeben, je nachdem welche Sprache in der Eingabe erkannt wurde
- Die erkannte Sprache wird im Property "language" mit ausgegeben
- Es gibt in den Skills ein Property "type" was dem Feld "Skill type" bei ESCO entspricht
- Es gibt in den Skills ein Property "reuse_level" was dem Feld "Skill reusability level" bei ESCO entspricht
- Ein Mapping auf K,L,S,T von ESCO lässt sich aufgrund der Datenstruktur von ESCO leider schlecht abbilden, weshalb wir erstmal mit den Feldern "type" und "reuse_level" arbeiten.
Schaut mal wie weit ihr damit kommt und wie wichtig ein K,L,S,T Mapping aus eurer Sicht wäre
- Zusätzlich gibt es in den Skills ein Property "distance" welches angibt wie nah laut KI der Skill am Eingabe Text liegt. Dieses Feld nutzen wir im Testing mit mycelia.

Updated documentation can be found here:
https://disruptive-elements.com/fileserver/skillnavigator/docs/

**Comment by YouQam** [comment]
@zven I think the issue is already resolved. If not can you guide me what exactly needs to be done?

**Comment by zven** [comment]
@YouQam Almost! ;-) The translation aspect does not require changes on our side but we also recieve some additional information with each response (something) I haven't pointed out too well, I must admit.

As you can see in the swagger documentation, we now also get a `type` (and `reuse_level`) for each skill we recieve. For now, we can ignore the latter but need to save the skill type as well.
I'm not entirely sure if we already do that properly: To my knowledge, we save an ESCO-skill either with type `skill` or `knowledge`. Please check how this maps to the data we get back.

**Comment by timber-they** [comment]
We don't currently handle the skill parameter. However, I think this is maybe worth a new ticket? Or at least the ticket should probably be renamed.
