### ISSUE TITLE
ui: upload custom graphics for badge creation without hexagon frame

### ISSUE THREAD

**Issue by zven** [mint-o-badges/badgr-ui#18]
Link to card on asana: https://app.asana.com/0/1205782519509072/1206556383404994

**Comment by zven** [comment]
@YouQam If you would have estimated this task: Would 16 h make sense?

**Comment by YouQam** [comment]
> [@YouQam](https://github.com/YouQam) If you would have estimated this task: Would 16 h make sense?

Yes.
