### ISSUE TITLE
Optimize "Institutionen" / Create Badge

### ISSUE THREAD

**Issue by Annicelia** [mint-o-badges/badgr-ui#180]
Can we add the "Meine" to the headline of the page "Institutionen" and add the "Badge erstellen" CTA within each Institution-Card? That would make it much, much more easier for users to get to "create a badge" because they don't have to click on the institution to find this CTA.

<img width="744" alt="Bildschirmfoto 2024-04-08 um 17 53 55" src="https://github.com/mint-o-badges/badgr-ui/assets/164371483/ee9e81b7-58e6-4a32-aa5a-8fe67f98cf77">

**Comment by Annicelia** [comment]
If it is not possible to add the button here for now, please add the subline: "Lege deine Institution an, um darüber Badges zu erstellen und zu vergeben".

**Comment by zven** [comment]
Just for reference: This is how it currently looks like.

<img width="1494" alt="Screenshot 2024-04-09 at 11 40 35" src="https://github.com/mint-o-badges/badgr-ui/assets/2930332/8732a013-8558-410b-b202-2f735c652273">

Todos:

- [ ] adjust the headline from "Institutionen" to "Meine Institutionen"
- [ ] add button "Neuen Badge erstellen" that links to the badge creation page
