### ISSUE TITLE
Competency levels still shown when creating a badge

### ISSUE THREAD

**Issue by TobiSchumacher** [mint-o-badges/badgr-ui#181]
**Name the test case**
I created a badge

**Describe the bug**
Competency level (A1) is still shown when looking at the badge and minimal length says "1 Stunden" even though the competencies in total are 240 minutes (4 hours)

![Screenshot_20240408-175607](https://github.com/mint-o-badges/badgr-ui/assets/164183217/4c27c91d-6b11-411c-823f-4bccd78b287b)

**Smartphone (please complete the following information; remove if not applicable):**

-   Device: Huawei Mate Lite 10
-   OS: Android
-   Browser: Firefox

**Additional context**
Add any other context about your observations here.

**Comment by zven** [comment]
The duration will be addressed in #159 

Here, we should only remove the now obsolete "Level" information from the system.
