### ISSUE TITLE
UI - Earners: Badge window is in English

### ISSUE THREAD

**Issue by TobiSchumacher** [mint-o-badges/badgr-ui#182]
**Name the test case**
Badge overview in English as a learner.

**Describe the bug**
When looking at a badge in the wallet as an earner, some of the words are in English

**Screenshots**

![Screenshot_20240408-171835](https://github.com/mint-o-badges/badgr-ui/assets/164183217/b418666b-37b2-4802-98c7-21eaa9e1e4ff)

**Smartphone (please complete the following information; remove if not applicable):**

-   Device: Huawei Mate 10 Lite
-   OS: Android
-   Browser: Firefox

**Comment by zven** [comment]
I agree:

<img width="1494" alt="Screenshot 2024-04-09 at 13 03 01" src="https://github.com/mint-o-badges/badgr-ui/assets/2930332/2e897015-546e-4490-ade7-f1a86f4fe484">

**Comment by timber-they** [comment]
Requested some changes
