### ISSUE TITLE
Login window needs to give link to registration

### ISSUE THREAD

**Issue by schmidfranzi** [mint-o-badges/badgr-ui#186]
**Name the test case**
Nutzer*in registrieren

**Describe the bug**
When I want to log in, there needs to be also a direct link with the words "Jetzt registrieren." that link brings the user to the register field.

**Screenshots**
<img width="597" alt="Screenshot 2024-04-08 at 20 30 35" src="https://github.com/mint-o-badges/badgr-ui/assets/164329233/670b6965-6a76-4c40-91de-f6e5dfe9f30f">

**Desktop (please complete the following information; remove if not applicable):**

-   OS: MacOS
-   Browser chrome

**Comment by zven** [comment]
@mpfeil New design can be found here: https://www.figma.com/file/rq5IOcBWjVAl7tmvtq0GqS/Use-Cases?type=design&node-id=2887-6682&mode=design&t=8QD6fG8uLVLR16Kb-4

As part of #150 we'll hone out a number of design topics as well.
