### ISSUE TITLE
Different outcomes from the AI competencies tool

### ISSUE THREAD

**Issue by schmidfranzi** [mint-o-badges/badgr-ui#187]
**Name the test case**
Badge erstellen - Kompetenzen definieren mit dem KI Tool

**Describe the bug**
When entering the "inhaltliche Beschreibung" the competencies that are listed are different from the competencies that are listed in the test-infrastructure that Jürgen provided. 

**Expected behavior**
Same competencies are listed

**Screenshots**
Here the screenshot from the OEB Website:
<img width="746" alt="Screenshot 2024-04-09 at 11 48 27" src="https://github.com/mint-o-badges/badgr-ui/assets/164329233/56283c0c-a910-4f02-8c2a-b5a0b3c12aba">
Here the screenshot from Jürgens test infrastructure
 
<img width="1201" alt="Screenshot 2024-04-09 at 11 50 47" src="https://github.com/mint-o-badges/badgr-ui/assets/164329233/53a2ee42-3563-42ef-8fe2-5d2b8c4d9164">

**Desktop (please complete the following information; remove if not applicable):**

-   OS: MacOS 
-   Browserchrome]

**Comment by zven** [comment]
@schmidfranzi Could you provide the text you used?

**Comment by schmidfranzi** [comment]
Sure: The text was:

We conduct a workshop. In this workshop, we work on the topic of natural climate protection and work in groups on an individual start-up idea related to climate protection. We want to enable the girls to create their own idea for a company that addresses the issue of climate protection. The girls work in groups and along the design thinking process.

**Comment by timber-they** [comment]
I can't reproduce this (anymore). Maybe the adjusted settings on Staging weren't loaded yet because the server had to be restarted (which I did in the meantime, for other reasons).

**Comment by zven** [comment]
We fixed it in #138
