### ISSUE TITLE
Badge creation: I can't type correctly on "Criteria"

### ISSUE THREAD

**Issue by IngaSchmidt** [mint-o-badges/badgr-ui#198]
**Name the test case**
Badge creation

**Describe the bug**
When I create a badge, I can't type correctly in the "Criteria" field (see video)

**To Reproduce**

1. Go to 'Badge erstellen'
2. Click on 'Kriterien'
3. Write something

**Screenshots**

https://github.com/mint-o-badges/badgr-ui/assets/164493443/cbc94168-7be8-405b-a704-f126690939e8

**Smartphone (please complete the following information; remove if not applicable):**

-   Device: Samsung Galaxy S21 FE
-   Browser: Chrome

**Comment by zven** [comment]
@jona159 I guess you'll address this issue with the text field in #149?

**Comment by zven** [comment]
@IngaSchmidt Does this issue still prevail in the current version that is released on the staging system?

**Comment by IngaSchmidt** [comment]
Now, it works. Thank you!

**Comment by zven** [comment]
Fixed by #149
