### ISSUE TITLE
"Download badge" doesn't work on my phone

### ISSUE THREAD

**Issue by IngaSchmidt** [mint-o-badges/badgr-ui#199]
**Name the test case**
Download badge

**Describe the bug**
"Download badge" doesn't work on my phone

**To Reproduce**

1. Go to 'E-Mails'
2. Click on 'Download badge'
3. See error: I am redirected to the website (s. Video)

**Screenshots**

https://github.com/mint-o-badges/badgr-ui/assets/164493443/b65320bb-61e0-4160-afb2-99d13cfc556a

**Smartphone (please complete the following information; remove if not applicable):**

-  Device: Samsung Galaxy S21 FE
-  Browser Samsung Internet

**Comment by zven** [comment]
@IngaSchmidt Being redirected to the page is part of the download functionality. You are not able to download the badge because the curtain is still activated in you mobile browser. Open https://staging.openbadges.education/public/start?curtainEnabled=false once before downloading the badge.

**Comment by zven** [comment]
@IngaSchmidt Did it work with the curtain disabled?

**Comment by IngaSchmidt** [comment]
Now, it works. Thank you!

**Comment by zven** [comment]
Great!

**Comment by zven** [comment]
Fixed by #209
