### ISSUE TITLE
Favicon (mini-Icon) in Browser Tab is still the old logo

### ISSUE THREAD

**Issue by schmidfranzi** [mint-o-badges/badgr-ui#206]
**Name the test case**
Go to OEB Website

**Describe the bug**
There is still the old logo in the browser tab.

**Expected behavior**
please add the new logo

**Screenshots**
<img width="95" alt="Screenshot 2024-04-10 at 16 36 11" src="https://github.com/mint-o-badges/badgr-ui/assets/164329233/550e05a1-f351-42bb-a399-8973e528a6b5">

 
**Desktop (please complete the following information; remove if not applicable):**

-   OS: MacOS 
-   Browser chrome

**Comment by zven** [comment]
@schmidfranzi This is your browser caching some data. Once you clean cookies and website data for this page, the new icon should appear.

**Comment by schmidfranzi** [comment]
@zven nice and true ;)
