### ISSUE TITLE
Send PDF Certificate along with link to Badge-PNG via e-Mail

### ISSUE THREAD

**Issue by Annicelia** [mint-o-badges/badgr-ui#207]
Can we send the PDF Certificate of the badge in the award-badge-e-mail as well so that learners can dowlnoad it right away?

**Comment by zven** [comment]
@Annicelia No, that's currently not possible. Atm, a PDF representation of the badge is only created when a logged in user triggers the download process explicitly.

**Comment by timber-they** [comment]
What will this certificate be used for? The way I understand it the current PDF export is just a plain document without any possibility of verification. This is in contrast to the PNG "baking" (which seems to have been removed from the application), where the badge verification details are stored in the metadata of the PNG. So we have multiple options here:
1. Send the "normal" PDF as attachment in the mail. This would then be the same PDF that users currently would export via they're badge details view
2. Change the image in the PDF to a baked image of the badge. We would then also need to implement some way of verifying / importing PDFs with baked images. This would be useless if the PDF was supposed to be printed. This looks exactly the same as the normal badge image. For example (with the old design):
![testBake](https://github.com/mint-o-badges/badgr-ui/assets/13370101/b35dde5d-cce1-4fc0-996c-ff6c1f380c2c)
3. Add a QR Code to the PDF
    1. Encode the JSON presentation of the badge in the QR Code. This would be quite a big QR-code like this: 
![qrBadge](https://github.com/mint-o-badges/badgr-ui/assets/13370101/8dcb3ace-4562-4d87-a816-6e72b330de43)
We would probably also want to add some way of scanning / uploading this QR code to import / verify the badge.
    2. Encode a link in the QR code, similar to the link one gets via the sharing dialog (like this: https://api.staging.openbadges.education/public/assertions/P9TxpND5S06MjpMsjMO9ww). This would merely redirect the user to the details view of the badge
4. Add the JSON to the PDF. This would be something like this:
```JSON
{"@context":"https://w3id.org/openbadges/v2","type":"Assertion","id":"https://api.staging.openbadges.education/public/assertions/dpCszjgOTIa-INzz1GxLQQ","badge":"https://api.staging.openbadges.education/public/badges/-HhA2ojBS0yTWxTGpUSnrA","image":"https://api.staging.openbadges.education/public/assertions/dpCszjgOTIa-INzz1GxLQQ/image","verification":{"type":"HostedBadge"},"issuedOn":"2024-04-11T10:52:19.110665+00:00","recipient":{"hashed":true,"type":"email","identity":"sha256$3aaa7de9e71a72e94301e5545668cdae75d8cb1b1bf94f39e4382adf33586bc5","salt":"bd9e83bbd8e4498e8f7cf5e5b3fcb03d"}}
```
Once again, we would need to implement something the user could do with this JSON

**Comment by zven** [comment]
@timber-they Thanks for the quite detailed overview! :-) Would it also be an option do offer a pdf download link (similar to how the badge is provided atm via email)? Opening the link would trigger the pdf creation process. As an added benefit, the users would always get the most recent certificate design (assuming that the design will be enhanced over time).

**Comment by zven** [comment]
I checked back with @schmidfranzi and we decided on two main aspects:
* The badge PDF will be send around via email as an attachment
* The link you mentioned in 3. ii is displayed in the PDF as a clickable link (not a QR code)

**Comment by zven** [comment]
When adding the link to the virtual badge to the pdf, we should also fix some UI-Issues:
- the badge name bleeds into the text
- stopwatch icon is pixelated and deformed


![Image](https://github.com/mint-o-badges/badgr-ui/assets/2930332/bcfb5d32-fdda-445d-9e06-80d8faff060f)

**Comment by jona159** [comment]
- [ ] generate PDF on the server
- [ ] fetch PDF from the server and render it in embed
- [ ] attach PDF to email
- [ ] remove PDF creation from frontend

**Comment by timber-they** [comment]
@jona159 this is still WIP though, right?

**Comment by jona159** [comment]
yes sorry, added ```WIP``` to the PR title

**Comment by zven** [comment]
Note: We had to temporarily revert the linked server PR since it was breaking the awarding of badges (done in this PR: https://github.com/mint-o-badges/badgr-server/pull/119)
We realised that badge awarding was broken while testing: https://github.com/mint-o-badges/badgr-server/issues/112
