### ISSUE TITLE
learners can request badge via QR code

### ISSUE THREAD

**Issue by YouQam** [mint-o-badges/badgr-ui#23]
After some back and forth we came up with a not too complicated way of handing out badges via QR codes: For each badge class, a member of an institution can create a QR code campaigns ("QR-Code-Vergabe" in German) that are bound to a specific badge.

User flow and designs can be found here: https://www.figma.com/design/rq5IOcBWjVAl7tmvtq0GqS/Use-Cases?node-id=5768-34956&t=wGv1F199LRx3P0F7-4

Note:

* each badge class can have 0-n QR code campaigns
* QR code campaigns can be edited
* For each campaign, a validity period can be (optionally) defined. If such a timeframe is defined, the link / sub-page that is created is accessible
* Once a user accesses this link, they can fill out a form with name and email address to "sign up" for receiving a badge. Those requests can then be seen in the institutions' badge detail view.
* If a QR code campaign is deleted, we remove all the information associated with it.

Open question:

* Which role is allowed to create, edit and delete campaigns?

**Comment by zven** [comment]
@Annicelia, can you give us a heads up once you are done with the mobile designs?

**Comment by Annicelia** [comment]
@zven I think I am done, if you need something else let me know!

**Comment by jona159** [comment]
UI: https://github.com/mint-o-badges/badgr-ui/pull/592
Server: https://github.com/mint-o-badges/badgr-server/pull/223
