### ISSUE TITLE
still test-institutions in the live-version 

### ISSUE THREAD

**Issue by JuliaKleeberger** [mint-o-badges/badgr-ui#235]
still test-institutions in the live-version 

**Describe the bug**
on the website openbadges.education, there are still test institutions if I open the menu "Institutionen". 
Please remove them from the running system.

**To Reproduce**

1. Go to 'https://openbadges.education/catalog/issuers'
2. Scroll down to the first four entries. 

**Screenshots**

![image](https://github.com/mint-o-badges/badgr-ui/assets/12052169/757c33c7-f4f0-437d-af13-39e0cb787118)

Please delete these four test institutions (see screenshot) 

**Desktop (please complete the following information; remove if not applicable):**

-   OS: [e.g. Windows 10, MacOS 14.03, Ubuntu]
-   Browser [e.g. chrome, safari]
-   Version [e.g. 22]

**Smartphone (please complete the following information; remove if not applicable):**

-   Device: [e.g. iPhone6]
-   OS: [e.g. iOS8.1]
-   Browser [e.g. stock browser, safari]
-   Version [e.g. 22]

**Additional context**
Add any other context about your observations here.

**Comment by zven** [comment]
@JuliaKleeberger Good point!
