### ISSUE TITLE
ui: update logos with higher resolution images

### ISSUE THREAD

**Issue by zven** [mint-o-badges/badgr-ui#239]
Atm, the funder (especially those) and project partner logos on the about page are used in a downscaled / low resolution. We need to replace them with higher resolution versions.

![Image](https://github.com/mint-o-badges/badgr-ui/assets/2930332/c04a1432-c222-49bc-94b0-ab83929e6bbc)

**Comment by zven** [comment]
Please contact me for accessing the higher resolution images

**Comment by zven** [comment]
Logos can be found here: https://cloud.opensenselab.org/f/507315 Unfortunately, we have the BMBF-Logo in a low resolution version only, for now.

**Comment by zven** [comment]
I added a high res version of the bmbf logo to the Nextcloud folder.

**Comment by YouQam** [comment]
> [@YouQam](https://github.com/YouQam) note that it seems as if you linked a wrong PR (I corrected it).

Thanks!
