### ISSUE TITLE
Badge background picture is not loading when icon is selected

### ISSUE THREAD

**Issue by schmidfranzi** [mint-o-badges/badgr-ui#242]
**Name the test case**
create a testcase

**Describe the bug**
when I add an icon for the badge it is not shown in the background polygone. only when I select without Hexagon Frame and deselect this 

**Expected behavior**
The selected icon is always shown in the hexagon background and it needs to be actively deselected, if you don't want to use the background

**Screenshots**
<img width="882" alt="Screenshot 2024-04-22 at 15 27 41" src="https://github.com/mint-o-badges/badgr-ui/assets/164329233/cfa3deab-d211-466c-b5dc-b898b210ed25">
<img width="918" alt="Screenshot 2024-04-22 at 15 27 47" src="https://github.com/mint-o-badges/badgr-ui/assets/164329233/68ecc8e5-65d3-4689-966c-4dc65caf6916">

<img width="889" alt="Screenshot 2024-04-22 at 15 27 53" src="https://github.com/mint-o-badges/badgr-ui/assets/164329233/b48d2172-0dd0-4a9b-80eb-92ba4ca6a6fb">

**Desktop (please complete the following information; remove if not applicable):**

-   OS: 
-   Browser chrome

**Comment by zven** [comment]
Might be fixed by #149

**Comment by zven** [comment]
outdated
