### ISSUE TITLE
AI Tool based suggestions can't handle question marks

### ISSUE THREAD

**Issue by schmidfranzi** [mint-o-badges/badgr-ui#243]
**Name the test case**
Creating a badge

**Describe the bug**
When I enter the text in the AI Tool - an error pops up

**Screenshots**
<img width="1090" alt="Screenshot 2024-04-23 at 08 19 14" src="https://github.com/mint-o-badges/badgr-ui/assets/164329233/fc8cd975-efcf-445e-a6a0-4c183780c6ef">

**Comment by zven** [comment]
Text, that does not work:

```
In diesem Deep Dive wist du zum Klimaexperten - Du lernst den Unterschied zwischen Wetter und Klima kennen - Wie funktioniert der Treibhauseffekt und warum sind wir auf eine gesunde Natur angewiesen - Woher wissen wir, dass sich das Klima verändert, wie hat es sich in den letzten Jahrhunderten verändert, welchen Einfluss haben wir auf den Klimawandel und welche Folgen hat der Klimawandel für uns heute und in Zukunft?
 
Übersetzt mit DeepL.com (kostenlose Version)
```

After tinkering a bit with the text it turns out that the `?` is the problem. My assumption is that we don't escape this character (and potentially other special characters) properly while parsing / creating the json.
