### ISSUE TITLE
Minutes can't be edited within the AI competencies

### ISSUE THREAD

**Issue by schmidfranzi** [mint-o-badges/badgr-ui#248]
**Name the test case**
Paste the test case here.
Create a badge

**Describe the bug**
When the competencies from the AI tool are displayed, I can't edit the individual minutes within one competence

**Expected behavior**
The minutes within each competence can be edited

**Screenshots**
<img width="685" alt="Screenshot 2024-04-22 at 15 51 09" src="https://github.com/mint-o-badges/badgr-ui/assets/164329233/aaa2c6b5-0342-42a2-845f-2fd0276af30d">

**Comment by timber-they** [comment]
@jona159 it would be nice if you'd also link the PRs yourself, then I don't have to search for them :)
