### ISSUE TITLE
Badges: Super-badges

### ISSUE THREAD

**Issue by jona159** [mint-o-badges/badgr-ui#26]
A super-badge is a collection of skill and knowledge badges that contains information about a specific competency for badge-earners (the learners), such as, for example, communication. Similar to the badge-collections, these competency-badges are also a container for various skill and knowledge badges, but they form in relation to specific competencies (defined by team mycelia/the community) and (usually) not in response to pursuing a specific learning activity. In the long run, the competency-badges should form automatically after a learner has collected enough related skill or knowledge badges and should grow as well (in terms of how much time a learner has invested in developing a specific competency). For the user research, we would like to have two to three pre-defined competencies (see also related wireframes) to ask the users about.

This ticket comes from [Asana](https://app.asana.com/0/1205782519509072/1206317315962964).

Estimated time this will take: 32h.

**Comment by zven** [comment]
duplicate
