### ISSUE TITLE
ui: use modern ui components

### ISSUE THREAD

**Issue by zven** [mint-o-badges/badgr-ui#260]
Atm, we are using the existing UI framework that came with the `badgr-ui`. Since it is largely undocumented (and somewhat unwieldly) we could consider using a well documented open source framework for _new_ features.

@jona159, @YouQam and @umut0 Since we'll adjust the user flows / styling as part of the badge creation process (see #150), it might make sense to use a new UI framewok here.

**Comment by mpfeil** [comment]
Not sure if you already decided on a "modern" ui component library or UI framework. I just came across this one here: https://www.spartan.ng/documentation/introduction

It looks like https://ui.shadcn.com/ that we used in other NextJS projects.

**Comment by timber-they** [comment]
@YouQam I approved the PR but since you requested changes, you also need to approve it.
