### ISSUE TITLE
ui: fill criteria field based on AI tool input

### ISSUE THREAD

**Issue by zven** [mint-o-badges/badgr-ui#268]
Atm, the (required) criteria field needs to be filled out manually. The issue here: Much content that is part of the criteria field is alreaday (ideally) contained in the course description and (AI generated) competencies.

Idea:

- fill out the criteria field based on the information that is contained in the competencies
- criteria field is read only and not an editable text field anymore

**Comment by zven** [comment]
@Annicelia We need input for the following areas of the comptency field
- text header / intro
- text for each competency + which information to include
- text footer (if needed)

**Comment by zven** [comment]
Content can can be found here: https://www.figma.com/file/rq5IOcBWjVAl7tmvtq0GqS/Use-Cases?type=design&node-id=2887-6097&mode=design&t=a2jnbGqOqytVEnIA-4

**Comment by timber-they** [comment]
@zven but how exactly should the criteia be extracted? If it's not copy pasting from either the input field or the AI descriptions, we would basically need another "AI" for this

**Comment by zven** [comment]
@timber-they Ah, looking at my description again, it's maybe not so clear.

The idea is indeed copying from the selected AI-generated competencies (= their names) and the names of the manually added competencies. So, some piece of code would need to keep the criteria field updated with
`Du hast erfolgreich an [copy of badge title] teilgenommen.`
In case it's a competency badge underneath we would also have a list like
```
Dabei hast du folgende Kompetenzen gestärkt:
- [ai competency name 1]
- [ai competency name 2]
- [ai competency name 3]
- [manual competency name 1]
- [manual competency name 3]
```

This would be done in the UI.
