### ISSUE TITLE
ui: remove duplicate pdf implementation

### ISSUE THREAD

**Issue by zven** [mint-o-badges/badgr-ui#280]
To provide a pdf version of a badge, we used to generate a pdf file in the UI. With #207 we also want to send pdf files via mail. Hence, they need to be generated on the server. Atm, #207 implements an additional pdf creation process on the server. That on should be used exclusively.

Todos:

- [ ] call pdf creation service that is running on server from ui
- [ ] remove ui pdf creation implementation

**Comment by timber-they** [comment]
Since #207 is actually still in progress, this ticket can't be worked on yet.

**Comment by jona159** [comment]
Done in #300

**Comment by zven** [comment]
done by #207
