### ISSUE TITLE
ui: add welcome page

### ISSUE THREAD

**Issue by zven** [mint-o-badges/badgr-ui#285]
Atm, when a user logs in for the first time (after successful account creation) they are forwarded to their (most likely empty backpack). Instead, a simple welcome page should be shown: https://www.figma.com/file/rq5IOcBWjVAl7tmvtq0GqS/Use-Cases?type=design&node-id=2887-5888&mode=design&t=8QD6fG8uLVLR16Kb-4

**Comment by umut0** [comment]
The user is forwarded to this page on registration/ first login: https://staging.openbadges.education/auth/welcome

What is this ticket for? Just change the wording of the Buttons?

**Comment by zven** [comment]
@umut0 Ah, both me and @Annicelia have not been aware that we already have that page. In that case, it's only about adjusting the text.
