### ISSUE TITLE
ui: update badge detail page

### ISSUE THREAD

**Issue by zven** [mint-o-badges/badgr-ui#288]
Our current badge detail page is still a bit of a mix and match between the old my badges design and the new CI. It should look like depicted here: https://www.figma.com/file/rq5IOcBWjVAl7tmvtq0GqS/Use-Cases?type=design&node-id=2887-6139&mode=design&t=8QD6fG8uLVLR16Kb-4

This includes, for example:

- removal of gray area spanning the upper third of the page
- re-position and re-design tags
- rounded corners for badge meta data
- recolor the competency boxes
- restyle the "badge awarded to list" in the bottom
- replace badge creation date with last badge edit date (if we save that)
- fix the email search function (currently broken)

When you start working on this page, it might also make sense to have a quick chat with @Annicelia

**Comment by jona159** [comment]
- [ ] removal of gray area spanning the upper third of the page
- [ ] re-position and re-design tags
- [ ] rounded corners for badge meta data
- [ ] recolor the competency boxes
- [ ] restyle the "badge awarded to list" in the bottom
- [ ] replace badge creation date with last badge edit date (if we save that)
- [ ] fix the email search function (currently broken)

**Comment by timber-they** [comment]
@jona159 are the two last points still open TODOs?

**Comment by jona159** [comment]
> [@jona159](https://github.com/jona159) are the two last points still open TODOs?

No, forgot to mark the checkboxes

**Comment by timber-they** [comment]
Most of this seems fine but I don't really understand most of the spartan / helm changes, so maybe someone with a better understanding should also review it.
