### ISSUE TITLE
ui: update badge awarding page

### ISSUE THREAD

**Issue by zven** [mint-o-badges/badgr-ui#289]
The badge awarding page should also be updated with the new design: https://www.figma.com/file/rq5IOcBWjVAl7tmvtq0GqS/Use-Cases?type=design&node-id=2887-6455&mode=design&t=8QD6fG8uLVLR16Kb-4

There are two new elements on top of the window:

- "Badge-Vorschau": the image of the badge
- "Zertifikats-Vorschau": is something like a small thumbnail preview of the pdf certificate. For now, it's only there to highlight that there is something like a certifcate. Hence, we do not need to create the actual pdf certificate yet. Instead, we simply take the badge image and put in into a frame that looks like our pdf certificates. @Annicelia will provide a suitable graphic.

When a badge was succesfully awarded, we should link to the badge detail view (in case we don't do that yet) and display something like a popup: https://www.figma.com/file/rq5IOcBWjVAl7tmvtq0GqS/Use-Cases?type=design&node-id=2887-6242&mode=design&t=8QD6fG8uLVLR16Kb-4

**Comment by Annicelia** [comment]
@zven Will this work? ![Zertifikat-Thumbnail-Badge-vergeben](https://github.com/mint-o-badges/badgr-ui/assets/164371483/830b0797-136b-48ff-8009-428194e78965)

**Comment by zven** [comment]
@Annicelia Looks suitable to me. 👍 In case we need adjustments, we'll ping you
