### ISSUE TITLE
ui: bulk awarding feature

### ISSUE THREAD

**Issue by zven** [mint-o-badges/badgr-ui#290]
Investigate if the bulk badge feature (for awarding badges) is still working: https://www.figma.com/file/rq5IOcBWjVAl7tmvtq0GqS/Use-Cases?type=design&node-id=2887-6935&mode=design&t=8QD6fG8uLVLR16Kb-4

In case the feature works as expected, also restyle the page. The "Beispiel-Vorlage" seems to be broke, for example. In addition, we also just require a list of email-addresses only.

**Comment by zven** [comment]
@Annicelia For the list of badge earners that one could upload, would it also make sense to have the names as well (potentially optional)?

**Comment by Annicelia** [comment]
@zven yes, I adapted the copy :)

**Comment by zven** [comment]
First step: fix csv file
