### ISSUE TITLE
ui: add our own thumbnail to video on front page

### ISSUE THREAD

**Issue by zven** [mint-o-badges/badgr-ui#296]
The thumbnail of the video on the landing page shows a thumbnail that does not match our new CI. The idea is to add custom image (that matches our CI) before / over the video.

**Comment by zven** [comment]
Similar to here: https://stackoverflow.com/questions/7199624/youtube-embedded-video-set-different-thumbnail

**Comment by zven** [comment]
@Annicelia Could you provide us with a suitable image?

**Comment by Annicelia** [comment]
@jona159 

![Vorschau-Bild Video](https://github.com/mint-o-badges/badgr-ui/assets/164371483/2e06ab0d-4cd9-4da6-a137-1925868c86ab)
![Vorschaubild-Video-Play](https://github.com/mint-o-badges/badgr-ui/assets/164371483/fc4ef0f5-5448-4141-880d-bc3d63d200a9)
