### ISSUE TITLE
uI: create typography classes / mixins und more reusable components

### ISSUE THREAD

**Issue by zven** [mint-o-badges/badgr-ui#306]
Currently we are copying all the tailwind classes to all the elements in the HTML all the time.

We could just create classes in the typography.scss for typography related things and create more reusable components based on spartan.

general
- [x] Typography
- [x] paddings / margins
- [ ] Notifications
- [x] Hover / active states

Reusable components
- [x] Buttons
- [x] Tables / Datatables
- [x] Inputfields
- [ ] Tabs
- [x] Accordion (done?)
- [x] Links
- [x]  Checkboxes

**Comment by YouQam** [comment]
@umut0 the linked PR seems to be related to ticket [#186](https://github.com/mint-o-badges/badgr-ui/issues/186)?

**Comment by umut0** [comment]
Link to showcase page: https://deploy-preview-299--openeducationalbadges.netlify.app/showcase
