### ISSUE TITLE
missing function: "Kompetenz hinzufügen"

### ISSUE THREAD

**Issue by JuliaKleeberger** [mint-o-badges/badgr-ui#307]
**Name the test case**
missing function: "Kompetenz hinzufügen"

**Describe the bug**
as an issuer, when you want to create a competency badge, you can go to "Händisch Kompetenzen hinzufügen". 
Here you can click on "Entfernen" > but if you decide afterwords you want to "Hinzufügen" there is no button that you can "Hinzufügen" 

**To Reproduce**

1. Go to 'Badge erstellen > Händisch Kompetenzen hinzufügen'
2. Click on 'Entfernen'
3. See you do not have the possibility to "Hinzufügen" anymore

**Expected behavior**
there should be still the button "Hinzufügen"
![image](https://github.com/mint-o-badges/badgr-ui/assets/12052169/a4cfbf38-3577-4ec8-b179-9114893989f4)
![image](https://github.com/mint-o-badges/badgr-ui/assets/12052169/b41dbb52-662f-4727-8354-8b8ba2a86442)

**Screenshots**

**Desktop (please complete the following information; remove if not applicable):**

-   OS: [e.g. Windows 10, MacOS 14.03, Ubuntu]
-   Browser [e.g. chrome, safari]
-   Version [e.g. 22]

**Smartphone (please complete the following information; remove if not applicable):**

-   Device: [e.g. iPhone6]
-   OS: [e.g. iOS8.1]
-   Browser [e.g. stock browser, safari]
-   Version [e.g. 22]

**Additional context**
Add any other context about your observations here.

**Comment by zven** [comment]
fixed by #317
