### ISSUE TITLE
ui: add section to mbr integration to about us page

### ISSUE THREAD

**Issue by zven** [mint-o-badges/badgr-ui#308]
On the about us page, we want to highlight the Mein Bildungsraum-integration. To do so, we'll add an extra section.

**Comment by zven** [comment]
@Annicelia will provide a design

**Comment by jona159** [comment]
@Annicelia Would it be possible for you to export the graphics individually? Also i have not yet found a mobile design, does it already exist?

**Comment by Annicelia** [comment]
@jona159 sure, do this files work for you? (I am working in the mobile design right now and let you now when I am done)
![MBR-Anbindung-1](https://github.com/mint-o-badges/badgr-ui/assets/164371483/9f7028e4-35d1-492e-8b4c-de08b391d14d)
![MBR-Anbindung-2](https://github.com/mint-o-badges/badgr-ui/assets/164371483/9e1031ad-5eaa-46bf-9d7f-ad170f773d9b)
![MBR-Anbindung-3](https://github.com/mint-o-badges/badgr-ui/assets/164371483/a9ef3e85-beca-4680-8036-3a02f4061da5)
![MBR-Anbindung-4](https://github.com/mint-o-badges/badgr-ui/assets/164371483/ed8a00a9-5f7a-4481-b698-947fc60e1b78)
![MBR-Anbindung-5](https://github.com/mint-o-badges/badgr-ui/assets/164371483/25e97e0f-1724-458e-9f8b-c4b8356ee63e)
![MBR-Anbindung-6](https://github.com/mint-o-badges/badgr-ui/assets/164371483/dde18b33-e41a-4d79-9057-d0c57b7c1a85)
![MBR-Anbindung-7](https://github.com/mint-o-badges/badgr-ui/assets/164371483/7465f6c0-b048-435f-9b79-966a4f417142)
![MBR-Anbindung-8](https://github.com/mint-o-badges/badgr-ui/assets/164371483/1c85a4b1-4293-40ee-a64c-3aa1c49225fc)
![MBR-Anbindung-Logo](https://github.com/mint-o-badges/badgr-ui/assets/164371483/5dbceeb6-a646-468e-a8f9-cdf479d82186)

**Comment by jona159** [comment]
@Annicelia yes these should work, thank you!

**Comment by Annicelia** [comment]
@jona159 
mobile is ready :) https://www.figma.com/design/rq5IOcBWjVAl7tmvtq0GqS/Use-Cases?node-id=1457-1366&t=ukT7BPUdx3A3prUc-4
![MBR-Anbindung-mobile1](https://github.com/mint-o-badges/badgr-ui/assets/164371483/1bde4b6c-5006-45fc-bbf1-a54936640cb3)
![MBR-Anbindung-mobile2](https://github.com/mint-o
![Bildschirmfoto 2024-05-21 um 10 54 49](https://github.com/mint-o-badges/badgr-ui/assets/164371483/74af398f-0a0d-4810-83a3-98ca71193538)
-badges/badgr-ui/assets/164371483/ac64159b-8996-41ac-b15e-fccd27e0be67)
