### ISSUE TITLE
wrong Url link 

### ISSUE THREAD

**Issue by JuliaKleeberger** [mint-o-badges/badgr-ui#310]
**Name the test case**
wrong URL-Link

**Describe the bug**
when I press the button "Zur Esco Suche" the english page appears - it should be the german page

**To Reproduce**

1. Go to 'Badge erstellen'
2. Click on 'Zur Esco Suche'
3. the website opens: https://esco.ec.europa.eu/en/classification/skill_main 

**Expected behavior**
in Step 3 it should be the following link: https://esco.ec.europa.eu/de/classification/skill_main 

**Screenshots**

**Desktop (please complete the following information; remove if not applicable):**

-   OS: [e.g. Windows 10, MacOS 14.03, Ubuntu]
-   Browser [e.g. chrome, safari]
-   Version [e.g. 22]

**Smartphone (please complete the following information; remove if not applicable):**

-   Device: [e.g. iPhone6]
-   OS: [e.g. iOS8.1]
-   Browser [e.g. stock browser, safari]
-   Version [e.g. 22]

**Additional context**
Add any other context about your observations here.

**Comment by zven** [comment]
fixed in #268
