### ISSUE TITLE
Create Badge: Land on the top of the page

### ISSUE THREAD

**Issue by schmidfranzi** [mint-o-badges/badgr-ui#323]
**Name the test case**
creating a badge

**Describe the bug**
When creating a badge, the site opens in the middle of the page. I need to scroll up first

**To Reproduce**
Go to my institution
click on create a badge
see where you land on the page

**Screenshots**
<img width="1426" alt="Screenshot 2024-05-21 at 11 09 27" src="https://github.com/mint-o-badges/badgr-ui/assets/164329233/3e5f641c-6d83-4e5c-98e5-2ddc29d20fec">

**Comment by jona159** [comment]
Does not seem to happen on staging anymore, maybe this was fixed by some other ticket recently

**Comment by zven** [comment]
already fixed

**Comment by zven** [comment]
already fixed
