### ISSUE TITLE
Rename Button Add Another Competency

### ISSUE THREAD

**Issue by schmidfranzi** [mint-o-badges/badgr-ui#324]
**Name the test case**
Create a Badge

**Describe the bug**
When creating a badge I added manually a competency. If I want to add another the button is names strangely. 
Please rename the button in: **Weitere Kompetenz hinzufügen**

**Screenshots**

<img width="1203" alt="Screenshot 2024-05-21 at 11 18 31" src="https://github.com/mint-o-badges/badgr-ui/assets/164329233/72b18844-99b0-4bd5-9ea4-95d2424a83e6">

**Comment by zven** [comment]
@schmidfranzi Which browser have you used for testing? I can't reproduce this on Firefox (MacOS).

Plus: Have you tried reloading (without loading the page from the cache) and/or deleted your cache first?

**Comment by zven** [comment]
Great!
