### ISSUE TITLE
!! Badge erstellen button does not work !!

### ISSUE THREAD

**Issue by schmidfranzi** [mint-o-badges/badgr-ui#325]
**Name the test case**
Create a badge

**Describe the bug**
@zven this is a real and urgent bug ;) : 
When creating a badge - the last final step does not work. Hitting the button Badge erstellen, does nothing.

**Comment by schmidfranzi** [comment]
It seems to come from the criteria definition. I get a failure within the criteria, but I can not add a text and therefore it won't let me create the badge. See Screenshot: 

<img width="1273" alt="Screenshot 2024-05-21 at 11 32 03" src="https://github.com/mint-o-badges/badgr-ui/assets/164329233/768b2deb-2ad1-4c78-aef9-c622833b749a">

**Comment by zven** [comment]
With #317 we fill the criteria field automatically. Apparently, we have not adjusted the check _if_ the field is filled or not.
