### ISSUE TITLE
ui: new institution can create a badge without verification (bug)

### ISSUE THREAD

**Issue by zven** [mint-o-badges/badgr-ui#339]
While creating badges is disabled `in issuer-detail-page` for new issuers before verification process, it's possible `in issuer-page` without verification.

**Comment by timber-they** [comment]
There seem to be two TODOs here:
- [ ] Disable badge creation for unverified issuers in the frontend (disable the button in the `in issuer-page`)
- [ ] Disable it in the backend (since this seems to be critical)

**Comment by timber-they** [comment]
There are two PRs: [frontend](https://github.com/mint-o-badges/badgr-ui/pull/360) and [backend](https://github.com/mint-o-badges/badgr-server/pull/126).
