### ISSUE TITLE
ui: fix map view of issuers

### ISSUE THREAD

**Issue by zven** [mint-o-badges/badgr-ui#341]
Map feature on the institutions page does not show any institutions unless you type something in the search box:

First:
![Image](https://github.com/mint-o-badges/badgr-ui/assets/2930332/8b627a34-7e41-427b-bc45-d20de78f3c62)

**Comment by Thiemann96** [comment]
fixed in #811

**Comment by umut0** [comment]
I think its better to give it ~80VH instead of fixed 384px
