### ISSUE TITLE
ui: font for FAQ in green footer is different than rest of page

### ISSUE THREAD

**Issue by zven** [mint-o-badges/badgr-ui#342]
I'm referring to the label `FAQ` here: 

![Image](https://github.com/mint-o-badges/badgr-ui/assets/2930332/0f7108f2-ffa9-4881-ab45-ea8bbe0af5d3)

It's actually the same in the Figma-designs

**Comment by YouQam** [comment]
It's different due to having different font-family `Inter`

![Image](https://github.com/user-attachments/assets/ba3533af-d965-4282-a40a-3b658193dd4a)

**Comment by jona159** [comment]
@YouQam i assume they did not choose this font-family on purpose in the design. Let`s just use the same font-family as for ```Impressum & Datenschutz```

**Comment by jona159** [comment]
@Annicelia could you maybe confirm if my assumption is correct that we should use the same font-family here (so ```rubik``` for FAQ as well?)

**Comment by Annicelia** [comment]
@jona159 yes, Rubik everywhere please :)
