### ISSUE TITLE
Issuer can share personalised badge of another person

### ISSUE THREAD

**Issue by schmidfranzi** [mint-o-badges/badgr-ui#345]
**Name the test case**
see the badges i already have issued

**Describe the bug**
As an issuer I can see who I issued the badges to. In this view the issuer can share the individual issued badge. That should not be possible. 
We need to look into that and clarify the functionalities. 

**To Reproduce**
Go to Meine Institutionen
Click on a badge that is issued several times
Go down to the list of email adresses
click on the three dots on the right side
click share
see what is possible

**Screenshots**

![Screenshot 2024-05-24 at 12 17 30](https://github.com/mint-o-badges/badgr-ui/assets/164329233/17b30a84-aec2-4a61-acb4-28e61fa82651)
![Screenshot 2024-05-24 at 12 17 30](https://github.com/mint-o-badges/badgr-ui/assets/164329233/17b30a84-aec2-4a61-acb4-28e61fa82651)
![Screenshot 2024-05-24 at 12 17 43](https://github.com/mint-o-badges/badgr-ui/assets/164329233/ef5a61e6-5807-4f2f-b43c-6e6fcb00c348)
![Screenshot 2024-05-24 at 12 17 43](https://github.com/mint-o-badges/badgr-ui/assets/164329233/ef5a61e6-5807-4f2f-b43c-6e6fcb00c348)

**Comment by schmidfranzi** [comment]
@Annicelia @zven wir müssen hier mal gemeinsam kurz in die Klärung gehen :)

**Comment by zven** [comment]
already fixed
