### ISSUE TITLE
ui: update ui elements with new ui classes / components

### ISSUE THREAD

**Issue by zven** [mint-o-badges/badgr-ui#347]
@umut0 did some great work with centralizing and optimizing our commonly used ui elements https://github.com/mint-o-badges/badgr-ui/issues/306

Neverthelesse, we still need to include those in our pages.

**Comment by umut0** [comment]
What needs to be done:

Go through components and:
- remove all references to the old css-classes
- use newly created OEB-Elements
- use the predefined paddings and margins
- create new OEB-Elements when needed and if nothing else exists yet
- check if new Layout works with existing component


Components to be checked:
- [ ] Navigation

**Comment by zven** [comment]
issue not needed anymore
