### ISSUE TITLE
server-ui: resend email confirmation after signing up

### ISSUE THREAD

**Issue by zven** [mint-o-badges/badgr-ui#353]
This issue was part of [#284](https://github.com/mint-o-badges/badgr-ui/issues/284). It's about adding an option to resend confirmation email after signing up.

See design:  https://www.figma.com/file/rq5IOcBWjVAl7tmvtq0GqS/Use-Cases?type=design&node-id=2887-5925&mode=design&t=8QD6fG8uLVLR16Kb-4

**Comment by YouQam** [comment]
To review the implementation of this ticket:
[server PR](https://github.com/mint-o-badges/badgr-server/pull/132)
[ui PR](https://github.com/mint-o-badges/badgr-ui/pull/377)

**Comment by jona159** [comment]
@YouQam I am not fully aware what the requirements for this ticket are. When i register an account and i click on ```Email erneut senden``` i get back the email: ```Bitte bestätige Deine zusätzliche E-Mail-Adresse.``` Shouldnt it resend the email ```Bestätige Deinen Account bei OpenEducationalBadges```? Or maybe we can have a quick call so you can explain the requirements to me?
