### ISSUE TITLE
ui: clean up different badge and institution views

### ISSUE THREAD

**Issue by zven** [mint-o-badges/badgr-ui#354]
Atm, we have a number of different views of badges, awarded badges (e.g. private or public) and institituions:

Institutions:
- https://staging.openbadges.education/issuer/issuers/HyFuQFGET5GeldrwLTOL-Q
- https://staging.openbadges.education/public/issuers/HyFuQFGET5GeldrwLTOL-Q

Badges:
- Issuer view of badge: https://staging.openbadges.education/issuer/issuers/HyFuQFGET5GeldrwLTOL-Q/badges/UodyGw3iQmeoaMXOniL2dQ
- View of awarded badge in backpack: https://staging.openbadges.education/recipient/earned-badge/Cu4KT64RQuWSuF_TgWqZkw
- Public view of badge class: https://staging.openbadges.education/public/badges/UodyGw3iQmeoaMXOniL2dQ
- Public assertion view (of awarded badge): https://staging.openbadges.education/public/assertions/23zj6bHpRM-TPZ7lnZC_aA

Todos:

- [ ] check if the list above is complete
- [ ] research: What are those separate views for?
- [ ] Can we centralize them in code? Just one view for institutions and badges? So far it looks like two to three different implementations to me
- [ ] Can we kick some of the views out?

**Comment by umut0** [comment]
This PR is for the badge Views. We will do the institutions in a separate PR.
