### ISSUE TITLE
ui: dates for badges in institution table are broken

### ISSUE THREAD

**Issue by zven** [mint-o-badges/badgr-ui#357]
See here:

![Image](https://github.com/mint-o-badges/badgr-ui/assets/2930332/ed3e5982-65e0-4f26-83d8-4c97f3b34f77)

**Comment by jona159** [comment]
will be fixed in #335

**Comment by timber-they** [comment]
Most of this seems fine but I don't really understand most of the spartan / helm changes, so maybe someone with a better understanding should also review it.
