### ISSUE TITLE
testing / development instance without PRs

### ISSUE THREAD

**Issue by zven** [mint-o-badges/badgr-ui#365]

**Comment by timber-they** [comment]
I already made the necessary code changes and created a server as duplicate of staging, which should then be available under develop.openbadges.education, but Christopher has yet to create the subdomain entry.

**Comment by timber-they** [comment]
[This PR](https://github.com/mint-o-badges/badgr-server/pull/128) of the backend also relates to this ticket.

**Comment by zven** [comment]
Subdomain should be added now

**Comment by timber-they** [comment]
@jona159 you seem to have forgotten to review the [backend PR](https://github.com/mint-o-badges/badgr-server/pull/128)

**Comment by timber-they** [comment]
There was a typo, so now there's another [PR](https://github.com/mint-o-badges/badgr-ui/pull/378)
