### ISSUE TITLE
Improve badge overview for institutions

### ISSUE THREAD

**Issue by TobiSchumacher** [mint-o-badges/badgr-ui#371]
**Badge overview for institutions**

**Describe the bug**
This is not a bug, but when clicking on an institution, I see an overview of all the badges that this institution has created, but I only see the badge visuals and not the name of the badge, which is confusing, particularly if an institution has multiple badges.

**Expected behavior**
Add the badge title next to the badge visual.

**Screenshots**
![Bildschirmfoto 2024-06-03 um 11 28 25](https://github.com/mint-o-badges/badgr-ui/assets/164183217/8becef58-ba35-40fc-bd2f-8d6b2e296c16)

**Desktop**

-   OS: macOS Sonoma 14.0
-   Browser: Chrome

**Comment by zven** [comment]
already fixed

**Comment by zven** [comment]
already fixed
