### ISSUE TITLE
unable to delete badge

### ISSUE THREAD

**Issue by Annicelia** [mint-o-badges/badgr-ui#374]
When trying to delete a badge from my institution (institution: mycelia, badge "Test Badge mit nicht ganz so langem Titel", I get this error notification: 
![Bildschirmfoto 2024-06-04 um 11 48 14](https://github.com/mint-o-badges/badgr-ui/assets/164371483/26c94c82-461d-43ec-b54a-91ff00a9edf2)

**Comment by zven** [comment]
@Annicelia Has this badge already been awarded to someone? If that is so, it needs to be revoked first before it can be deleted.

**Comment by Annicelia** [comment]
ah yeah now it is possible to delete it, thanks

**Comment by zven** [comment]
nothing that needs to be done here, hence closed
