### ISSUE TITLE
new subpage: "Aktivitäten"

### ISSUE THREAD

**Issue by zven** [mint-o-badges/badgr-ui#381]
Desktop: https://www.figma.com/design/rq5IOcBWjVAl7tmvtq0GqS/Use-Cases?node-id=5378-3274&t=dirISV0hvTb7MAYb-4
Mobile: https://www.figma.com/design/rq5IOcBWjVAl7tmvtq0GqS/Use-Cases?node-id=5080-34076&t=dirISV0hvTb7MAYb-4

Please make the Timeline "zoomable"
![Image](https://github.com/mint-o-badges/badgr-ui/assets/164371483/46fdfef3-cd0b-4b06-a3e8-dafbd5bb092c)

Revised Menu Structure: 
Über OEB 
-> Projektverbund (former "Über OEB")
**-> Aktivitäten**
-> Team

**Comment by Annicelia** [comment]
@zven the content of this page has been supplemented by the "Banner Begleitforschung": https://www.figma.com/design/rq5IOcBWjVAl7tmvtq0GqS/Use-Cases?node-id=5378-3274&t=IfbUzBNm9jcHQnCO-4

![Image](https://github.com/user-attachments/assets/8d96d00a-a5ce-4d1d-a8e1-b306dcddf958)
![Image](https://github.com/user-attachments/assets/f0779d23-20a6-4508-85b6-f52953768d2f)
[Download-Buchem.pdf](https://github.com/user-attachments/files/16228737/Download-Buchem.pdf)
[Download-Ehlers.pdf](https://github.com/user-attachments/files/16228736/Download-Ehlers.pdf)
[Download-Value-For-Good.pdf](https://github.com/user-attachments/files/16228735/Download-Value-For-Good.pdf)
![Image](https://github.com/user-attachments/assets/2c6645fd-8224-4b78-808e-10df7737a6ed)
![Image](https://github.com/user-attachments/assets/c5ae241c-08c9-486b-9686-7fa88a546224)
![Image](https://github.com/user-attachments/assets/f564a65d-bc39-43ab-b08d-5481efae3e8f)
![Image](https://github.com/user-attachments/assets/23580caf-1592-48ed-941f-f52a5f6e1418)

**Comment by zven** [comment]
Please leave out the PDF files for now: We first need to clarify how / where to host them or if we can simply check them into the repository.

**Comment by zven** [comment]
Latest link to designs: https://www.figma.com/design/rq5IOcBWjVAl7tmvtq0GqS/Use-Cases?node-id=5378-3274&t=jnNAl3K85tG41BCk-4

**Comment by jona159** [comment]
@Annicelia could you also provide the images for the sections "Technik", "Community & Reallabore" and "Begleitforschung" ?

**Comment by zven** [comment]
Update: We might do this (in the future) via a CMS, details are currently still discussed.

**Comment by zven** [comment]
Will be done with CMS system in future. Hence, nothing to do for us here.
