### ISSUE TITLE
Badge Image Size needs to be scaled

### ISSUE THREAD

**Issue by schmidfranzi** [mint-o-badges/badgr-ui#386]
**Name the test case**
Creating a Badge with an individual badge image

**Describe the bug**
When uploading an individual badge image, the image is either framed with the preset badge frame or the individual badge image is too small. 

**Expected behavior**
the individual badge image is used and scaled to the size filling up the same size as the preset badge frame.

**Screenshots**

<img width="1372" alt="Screenshot 2024-06-11 at 15 09 54" src="https://github.com/mint-o-badges/badgr-ui/assets/164329233/bc3059d7-0172-4c77-afc5-0130672f73ae">

**Desktop (please complete the following information; remove if not applicable):**

-   OS: [e.g. Windows 10, MacOS 14.03, Ubuntu]
-   Browser [e.g. chrome, safari]
-   Version [e.g. 22]

**Smartphone (please complete the following information; remove if not applicable):**

-   Device: [e.g. iPhone6]
-   OS: [e.g. iOS8.1]
-   Browser [e.g. stock browser, safari]
-   Version [e.g. 22]

**Additional context**
Add any other context about your observations here.

**Comment by zven** [comment]
view is outdated and already fixed
