### ISSUE TITLE
ui: update ai tool info text on badge creation page

### ISSUE THREAD

**Issue by zven** [mint-o-badges/badgr-ui#389]
Based on the legal input, we should adjust the following things:

Todos:

- [x] Add the following sentence: `Bitte trage hier keine biographischen / persönlichen Informationen ein.`

**Comment by YouQam** [comment]
@zven are you referring to this?

![Image](https://github.com/mint-o-badges/badgr-ui/assets/40634685/04209c6c-456d-4fe7-b60d-1e27d12e6a9e)

**Comment by zven** [comment]
@YouQam Oooops, my bad! I meant section three `3. Badge mit Kompetenzen befüllen`. Here, please add the sentence after `Füge die inhaltliche Beschreibung deines Lehrangebots in das Textfeld ein.`



![Image](https://github.com/mint-o-badges/badgr-ui/assets/2930332/a2c12fe9-cc44-4f3c-b07c-71d83ce33393)
