### ISSUE TITLE
Registering new account not possible, because I don't receive a confirmation e-mail (posteo email)

### ISSUE THREAD

**Issue by TobiSchumacher** [mint-o-badges/badgr-ui#405]
**Registering new account not possible**

**Describe the bug**
When I try to register a new account, I don't receive a confirmation e-mail (at least up until 10 minutes after registering the account, my be it just takes a long time). I tried it with three different e-mail addresses, I also looked in my spam folder and also choose staging.openbadges.education (where I tested) as an exception for the spam filter so that e-mails from the domain should not land in my spam. 

**To Reproduce**

Just register an account.

**Expected behavior**
I should receive a confirmation mail

**Desktop:**

-   OS: macOS Sonoma 14.0
-   Browser: Chrome

**Comment by zven** [comment]
@TobiSchumacher When (as in date / time) did that happen exactly?

**Comment by TobiSchumacher** [comment]
@zven That happened on Monday, 17.06. at around 10.30/11.00

**Comment by YouQam** [comment]
- [ ]  contact chris

**Comment by TobiSchumacher** [comment]
@YouQam I received the email you sent to my posteo email address. I will try to reproduce the bug as it also might have also been caused by the additional email addresses I created for testing not working properly. I'll keep you updated.

**Comment by zven** [comment]
I also tried signing up with a posteo email address few weeks ago and today and it works (albeit sample size n=2).

**Comment by YouQam** [comment]
After discussing the issue with Chris, I think this is not a posteo issue and it can be that a specific email had been marked as spam locally, on the users device or at posteo and there is not much that can be done about it.
