### ISSUE TITLE
Not receiving an issued badge when using posteo e-mail (posteo email)

### ISSUE THREAD

**Issue by TobiSchumacher** [mint-o-badges/badgr-ui#407]
**Not receiving an issued badge when using posteo e-mail**

**Describe the bug**
When I issue a badge to my posteo e-mail address, I don't receive it. This seems to be a bug that occurs when interacting with posteo e-mail, as issuing a badge to a different e-mail address works without problem.

**To Reproduce**
Just issue a badge to someone with a posteo e-mail address.

**Expected behavior**
The badge should be issued to my posteo e-mail address.

**Desktop:**

-   OS: macOS Sonoma 14.0
-   Browser: Chrome

**Comment by zven** [comment]
Posteo is known to be quite strict with potential spam. We'll need to check the logs. Can you when have you awarded that badge exactly? And are you able to receive other OEB emails with this email address?

**Comment by YouQam** [comment]
I checked the logs and it seems to be a Posteo email issue. I'm trying with Chris to find a solution for it.

**Comment by zven** [comment]
See my comment here: https://github.com/mint-o-badges/badgr-ui/issues/405
(short: works with the posteo addresses I tested)

**Comment by YouQam** [comment]
See final comment here: https://github.com/mint-o-badges/badgr-ui/issues/405
