### ISSUE TITLE
Badge frame is not created (safari)

### ISSUE THREAD

**Issue by schmidfranzi** [mint-o-badges/badgr-ui#409]
**Name the test case**
Creating a badge

**Describe the bug**
When creating a competencies Badge the icon is not framed by the preset badge frame. 

**Expected behavior**
The badge is visualised correctly with the icon form the noun project and the preset frame (nonagon)

**Screenshots**

<img width="1158" alt="Screenshot 2024-06-17 at 12 28 11" src="https://github.com/mint-o-badges/badgr-ui/assets/164329233/44d8e4e1-912e-44fe-9506-b701c7281f0c">

**Desktop (please complete the following information; remove if not applicable):**

-   OS: Mac
-   Browser Safari

**Comment by zven** [comment]
@schmidfranzi Does the problem also encounter in another browser?

**Comment by zven** [comment]
possibly related to #343

**Comment by schmidfranzi** [comment]
It seems to work in chrome @zven

**Comment by zven** [comment]
@jona159 and @YouQam Any news here?

**Comment by YouQam** [comment]
> [@jona159](https://github.com/jona159) and [@YouQam](https://github.com/YouQam) Any news here?

The issue occurred due to unexpected behavior of `async pipe` when using `safari` browser. I found a workaround for it, I just need to do more testing to ensure it works fine with other browsers.

**Comment by YouQam** [comment]
For reviewers: to reproduce the issue with current version you need to reopen safari after clearing cache.
