### ISSUE TITLE
captcha doesn`t load

### ISSUE THREAD

**Issue by schmidfranzi** [mint-o-badges/badgr-ui#411]
**Name the test case**
Creating an account

**Describe the bug**
Creating an account the capture interface doesn`t load properly

**Screenshots**

<img width="967" alt="Screenshot 2024-06-17 at 13 05 25" src="https://github.com/mint-o-badges/badgr-ui/assets/164329233/c7bc78f0-ad5a-40d2-a5fc-4a9fa1ca80e2">

![IMG_BCBE01AFB6A7-1](https://github.com/mint-o-badges/badgr-ui/assets/164329233/3930c7b0-378c-4006-bae4-31c2ab5e04f6)

**Desktop (please complete the following information; remove if not applicable):**

-   OS: Mac
-   Browser Safari

Mobile
- Safari

**Comment by zven** [comment]
@schmidfranzi Have you tried clicking on the text `Ich bin kein Roboter`?
@jona159 That is everything you need to do, right?
