### ISSUE TITLE
Minutes are Limited within the competencies

### ISSUE THREAD

**Issue by schmidfranzi** [mint-o-badges/badgr-ui#418]
**Name the test case**
Create a badge and add competencies

**Describe the bug**
When creating a badge adding the minutes for one competence, I enter a high number (over 1000), because the course was over half a year. I get a failure message. It seems that the minutes are limited. However a course can have this length.

**Expected behavior**
there shouldn't be a limit to the minutes entered.

**Screenshots**
![Screenshot 2024-06-20 at 12 22 50](https://github.com/mint-o-badges/badgr-ui/assets/164329233/6c2b8380-9ae7-474d-9712-f1a53284c62e)

**Comment by zven** [comment]
remove limit
