### ISSUE TITLE
Overlapping graphic in account confirmation email

### ISSUE THREAD

**Issue by schmidfranzi** [mint-o-badges/badgr-ui#419]
**Name the test case**
create an account

**Describe the bug**
graphic in email overlaps the text. See the green circle of rays. 

**Screenshots**
![Screenshot 2024-06-20 at 14 32 48](https://github.com/mint-o-badges/badgr-ui/assets/164329233/1fe34701-8f2f-4d4d-805f-ee94a22cb356)

**Comment by zven** [comment]
Might be one of those illusive email client issues. Suggestion: We try to fix it with a timebox for 2 hours. If we don't have a solution then, we simply remove the backgroudn image / sunburst

**Comment by schmidfranzi** [comment]
works for me :)
