### ISSUE TITLE
ui | server: enable deletion of users

### ISSUE THREAD

**Issue by zven** [mint-o-badges/badgr-ui#425]
Apparently, there is no way in the UI to delete your own user.

Todos:

- [ ] Research: What happens now if a user is deleted? Do their badges disappear as well?
- [ ] Research: What happens if a user is deleted? Are related institutions and badges also deleted? 
- [ ] add a `delete user button` in the profile view

**Comment by timber-they** [comment]
Duplicate of #421?

**Comment by timber-they** [comment]
To answer the questions though: Nothing is deleted / disappears. The ownership of the issuer is adjusted as needed, if possible (as soon as the relevant ticket is merged).

**Comment by zven** [comment]
duplicate of #421
