### ISSUE TITLE
ui: limit badge title length to 70 characters

### ISSUE THREAD

**Issue by zven** [mint-o-badges/badgr-ui#436]
Long badge titles either take up a lot of space or need to be shortened. We should enforce the limit of 70 characters on the badge creation form:

![Image](https://github.com/mint-o-badges/badgr-ui/assets/2930332/ab596fc2-b981-4011-8a1e-8ed307350eeb)

**Comment by jona159** [comment]
I think we should enforce this limit already on staging

**Comment by zven** [comment]
Ah, I didn't know that. Great!
