### ISSUE TITLE
ui: can't search for badge icons

### ISSUE THREAD

**Issue by zven** [mint-o-badges/badgr-ui#44]
Searching for a stock icon for a badge does not work.

![Image](https://github.com/mint-o-badges/badgr-ui/assets/2930332/50f8fced-6a91-49dc-b49c-d84efc97b20e)

**Comment by zven** [comment]
maybe subscription for thenounproject.com

**Comment by zven** [comment]
Check, we need to generate an API key from the openSenseLab the noun project account and add it to our system

**Comment by timber-they** [comment]
So we already have an account for the noun project? Who has access to it?
