### ISSUE TITLE
UI: Feedback "Attention Undefined" after trying to register with an email that I already registered with

### ISSUE THREAD

**Issue by TobiSchumacher** [mint-o-badges/badgr-ui#441]
**"Undefined" Feedback**
When I try to register with an email address that I already have an OEB account with, I receive a feedback "Attention Undefined" (s. screenshot) and I don't know what exactly went wrong. 

**Expected behavior**
It would be ideal, if I receive a feedback explaining what exactly went wrong (in this case: "There is already a registered account with this email address").

**Screenshots**
![Bildschirmfoto 2024-06-26 um 15 58 18 2](https://github.com/mint-o-badges/badgr-ui/assets/164183217/7b23f3fd-e8b0-498d-9a9b-76492a5829e7)

**Desktop (please complete the following information; remove if not applicable):**

-   OS: MacOS Sonoma 14.0
-   Browser: Chrome

**Comment by jona159** [comment]
Should be fixed by #442
