### ISSUE TITLE
ui: wrong/missing attention msg when creating an account with an existing email

### ISSUE THREAD

**Issue by zven** [mint-o-badges/badgr-ui#442]
**staging (wrong msg):**
![Image](https://github.com/mint-o-badges/badgr-server/assets/40634685/57adf095-b763-4e6f-bc08-a58f12c13298)

**production (correct msg):**
![Image](https://github.com/mint-o-badges/badgr-server/assets/40634685/8230fd7b-638a-48ad-a8a5-ac8a014cf126)

**Comment by YouQam** [comment]
It turned out that this issue occurred due to updating error-handling while adding captche impl.  [Feat/captcha #282](https://github.com/mint-o-badges/badgr-ui/pull/282), now it should work properly.
