### ISSUE TITLE
ui: adjust institution ui based on role

### ISSUE THREAD

**Issue by zven** [mint-o-badges/badgr-ui#446]
Mitarbeiter:innen are not able create a badge but are only informed in the last step of the badge creation process via a error message without any informative content.

Instead, we should rather hide / gray out where appropriate the UI elements for those roles that are not allowed to perform thos actions (i.e. badge creation etc.)

**Comment by zven** [comment]
waiting: We need to clarify who is allowed to do what

**Comment by zven** [comment]
Eigentümer:in:
Vollzugriff auf alle Funktionen (inkl. Hinzufügen/Entfernen von Editor:innen und Mitarbeiter:innen; Möglichkeit, Details der Institution zu bearbeiten; Erstellen, Löschen und Verleihen von Badges, Lernpfaden und Lernpfad-Badges).
Editor:in: Volle Rechte zum Erstellen, Löschen und Vergeben von Badges und Lernpfaden.
Mitarbeiter:in: Möglichkeit, die von Eigentümer:innen/Editor:innen erstellten Badges zu vergeben (direkt oder durch Erstellen einer QR-Code-Vergabe)

**Comment by zven** [comment]
Does only partain to roles of institutions

**Comment by YouQam** [comment]
> Eigentümer:in: Vollzugriff auf alle Funktionen (inkl. Hinzufügen/Entfernen von Editor:innen und Mitarbeiter:innen; Möglichkeit, Details der Institution zu bearbeiten; Erstellen, Löschen und Verleihen von Badges, Lernpfaden und Lernpfad-Badges). Editor:in: Volle Rechte zum Erstellen, Löschen und Vergeben von Badges und Lernpfaden. Mitarbeiter:in: Möglichkeit, die von Eigentümer:innen/Editor:innen erstellten Badges zu vergeben (direkt oder durch Erstellen einer QR-Code-Vergabe)

@zven  I've updated the ui to fit the description you made. I'll put this ticket in next again to re-check it when learn-path is merged.
