### ISSUE TITLE
ui: badge creation with missing image -> scroll to image

### ISSUE THREAD

**Issue by zven** [mint-o-badges/badgr-ui#447]
When a user creates a badge and some mandatory input field is still empty, the page scrolls to that input field. However, this does not yet happen for the image.

Todos:

- [x] if the image in the badge creation view is missing and the user clicks on the "Badge erstellen"-button, the page should scroll to the empty image upload / creation field

**Comment by YouQam** [comment]
This ticket consist of two bugs:
- [ ] page should scroll to the empty image when trying to create/update a badge
- [ ] With `competency badge type` scrolling to empty image doesn't occur from first time (only from second time)
