### ISSUE TITLE
ui: display competencies in grey

### ISSUE THREAD

**Issue by zven** [mint-o-badges/badgr-ui#449]
See here https://www.figma.com/design/rq5IOcBWjVAl7tmvtq0GqS/Use-Cases?node-id=4929-42007&t=ILkUKYCBK1el3JF5-4

We should use gray boxes wherever we use competencies.

**Comment by zven** [comment]
This also includes the exported PDF: https://www.figma.com/design/rq5IOcBWjVAl7tmvtq0GqS/Use-Cases?node-id=5004-12192&t=E8G7aJR3oIxpeTQO-4

**Comment by jona159** [comment]
Server PR to rework competencies in PDF: [183](https://github.com/mint-o-badges/badgr-server/pull/183)
