### ISSUE TITLE
registration leads to error

### ISSUE THREAD

**Issue by zven** [mint-o-badges/badgr-ui#45]

**Comment by timber-they** [comment]
It seems this is also solved by setting the SITE_ID in the backend back to 2 (in #19 / #20 of the server project).

**Comment by timber-they** [comment]
It seems the registration somewhat works, but an error is printed and no confirmation mail is sent out

**Comment by timber-they** [comment]
The error message I fixed in the code and created a PR for it. The confirmation mail seems to be a server configuration error, so I'm creating a new issue for that.

**Comment by timber-they** [comment]
Nevermind, the confirmation mail just seems to take 10 minutes to arrive, so I closed the other issue on that topic.
