### ISSUE TITLE
ui: fix async issues on badge creation page

### ISSUE THREAD

**Issue by zven** [mint-o-badges/badgr-ui#480]
Due to some issues with `async` calls on the badge creation page, we need to call some functions 2 - 3 times (otherwise some things don't work). We should investigate what goes wrong and fix those issues.

**Comment by timber-they** [comment]
It seems that removing all calls to `adjustUploadImage` seems to fix the errors and I don't see why it's necessary. However, there were comments stating that this breaks on Safari. I can't easily use Safari in Linux, so maybe someone with a Mac can confirm that this now re-introduces the error of the visual disappearing? And maybe someone can also find out *why* / provide some helpful log messages or similar?

**Comment by zven** [comment]
@timber-they Pleas create a pull request with the corresponding changes that need to tested on Safari. I can do the testing, thing.

**Comment by zven** [comment]
@timber-they I'd suggest that @YouQam takes over this issue since they can test on Safari while developing.

**Comment by timber-they** [comment]
@zven regarding your older comment: Someone had already tested it and it had indeed caused problems in Safari. I think it makes sense for Yousef to take over.

**Comment by zven** [comment]
@YouQam Did your investigations yield any results so far?

**Comment by YouQam** [comment]
> [@YouQam](https://github.com/YouQam) Did your investigations yield any results so far?

Yes, I found what was the issue and already resolved part of it. Will add more details later today.

**Comment by YouQam** [comment]
**Update:** fixing async issues causes three issues. Two are only occurring with safari.

- [ ] Not showing badge frame after selecting an image for first time (only with Safari)
    - This occurs due to large size of competency.svg and participation.svg frame files about `60 KB` compared to `2 KB` with old frames.
    - Needs to reduce the above mentioned files to resolve the issue.
- [ ] Badge image is not uploaded from first time. This occurs when trying to change badge image (only with Safari)
- [ ] Changing badge category doesn't change the frame.

**Comment by zven** [comment]
@YouQam I talked to @Annicelia and she looks into making the SVG files smaller.

@Annicelia Can you keep us posted here and, if it works, upload some smaller SVGs here?

**Comment by Annicelia** [comment]
@YouQam I don't know the current size, these new files are 6 kb each – let me know whether that's small enough
![Kompetenz-Badge-smaller](https://github.com/user-attachments/assets/c0edd1e2-7942-4d94-a604-4d1b80bacfe4)
![TN-Badge-smaller](https://github.com/user-attachments/assets/6293e635-d366-40c7-bdbe-5de8eea65916)

**Comment by YouQam** [comment]
> [@YouQam](https://github.com/YouQam) I don't know the current size, these new files are 6 kb each – let me know whether that's small enough ![Kompetenz-Badge-smaller](https://github.com/user-attachments/assets/c0edd1e2-7942-4d94-a604-4d1b80bacfe4) ![TN-Badge-smaller](https://github.com/user-attachments/assets/6293e635-d366-40c7-bdbe-5de8eea65916)

Thank you @Annicelia! The new files' size is perfect.

**Comment by timber-they** [comment]
Someone else needs to approve this PR because I created it.
