### ISSUE TITLE
Badge-Vergabe: "Empfänger:in mit E-Mail benachrichtigen" als Default

### ISSUE THREAD

**Issue by Annicelia** [mint-o-badges/badgr-ui#488]
![Bildschirmfoto 2024-07-15 um 12 07 00](https://github.com/user-attachments/assets/2d472a44-1f21-4e56-98de-a4aa97fd947f)
please make the checkbox "Empfänger:in mit E-Mail benachrichtigen" to be already selected per default

**Comment by jona159** [comment]
Should be fixed by #504
