### ISSUE TITLE
KI Tool: design of the competencies

### ISSUE THREAD

**Issue by Annicelia** [mint-o-badges/badgr-ui#489]
please adapt the new look of the competencies in the KI Tool as well so that they look like this: 
<img width="391" alt="Bildschirmfoto 2024-07-15 um 12 20 23" src="https://github.com/user-attachments/assets/143c9e63-9239-4880-a26e-be34563ad34a">

**Comment by zven** [comment]
@Annicelia Competencies that the user wants to add to the badge are also highlighted in green?

**Comment by zven** [comment]
@Annicelia I just realized that you added the link to ESCO and the info if it's a skill or knowledge. 👍
