### ISSUE TITLE
Badge Ansicht Issuer: click on [E] -> error

### ISSUE THREAD

**Issue by Annicelia** [mint-o-badges/badgr-ui#491]
after creating the badge when klicking on the "E" in the competencies, no link to ESCO opens but this error notification (Firefox)
![Bildschirmfoto 2024-07-15 um 12 30 07](https://github.com/user-attachments/assets/1bfdb4e5-85ca-4e95-ba97-0913210d21b5)

**Comment by umut0** [comment]
I can not reproduce this. Can you name the Badge/Competency where this is happening?

**Comment by Annicelia** [comment]
It didn't happen this time, so I think we can close the issue

**Comment by zven** [comment]
closed because we can't reproduce it
