### ISSUE TITLE
"Preview" of badge and Pdf Template needs to have text in it

### ISSUE THREAD

**Issue by schmidfranzi** [mint-o-badges/badgr-ui#492]
**Name the test case**
award a badge

**Describe the bug**
when awarding a badge the preview is new and a great feature, however it doesn't quite give the right informaiton. It only shows the Pictures - but the pdf should at least show the title and some structure of the badge. 
 

**Expected behavior**
That we see the preview of the badge and the pdf but without the name / or the identifier

**Screenshots**

<img width="1434" alt="Screenshot 2024-07-15 at 12 10 08" src="https://github.com/user-attachments/assets/eca12faf-3475-4f2a-8175-ecf626ff0451">

**Comment by zven** [comment]
@schmidfranzi This is really just a placeholder that contains the badge image with a frame around that resembles the PDF certificate. At this point, we don't have a baked / awarded badge yet and thus don't create an actual PDF file.

**Comment by jona159** [comment]
This was done as part of #608
