### ISSUE TITLE
ui: make badge earner name mandatory

### ISSUE THREAD

**Issue by zven** [mint-o-badges/badgr-ui#497]
Todos:

- [x] make badge earner name mandatory in input field on badge awarding page
- [ ] wherever the name of a user is used in conjunction with a badge (e.g. for PDF creation on website by user) the name that is stored in the badge is used (and not the one in the profile) -> do this only if a name is present in the badge. If there is now name (we store the name only since a few weeks), take the profile name.

**Comment by timber-they** [comment]
@zven I feel like these are two different issues. I'm gonna start by making the name mandatory, but maybe we should create a second card for the second TODO?

**Comment by timber-they** [comment]
I've created a [second card](https://github.com/orgs/mint-o-badges/projects/2/views/1?pane=issue&itemId=72697775) for the second TODO.
