### ISSUE TITLE
ui: update logo (again)

### ISSUE THREAD

**Issue by zven** [mint-o-badges/badgr-ui#501]
Since our current logo can't be printed properly we got yet another on. ;-)

![Image](https://github.com/user-attachments/assets/984cc189-ab84-46f7-8392-829ee99991e6)

**Comment by jona159** [comment]
Server: https://github.com/mint-o-badges/badgr-server/pull/192 
UI: https://github.com/mint-o-badges/badgr-ui/pull/505

**Comment by zven** [comment]
reopened because some logos are still old

**Comment by jona159** [comment]
@Annicelia would it be possible to also provide a new logo for this version: 

![Image](https://github.com/user-attachments/assets/0f4f1658-15ff-4dbd-ac07-c2bea10fa93a)

**Comment by Annicelia** [comment]
sure :)
![2_MOB_Signet_RGB](https://github.com/user-attachments/assets/2bc19c4a-4610-4c33-bdd7-c4d9d0719178)
![2_MOB_Signet_RGB](https://github.com/user-attachments/assets/8de7bd6c-a33d-40b2-af44-3eb9dd74cfe7)
![2_MOB_Signet_RGB](https://github.com/user-attachments/assets/f246598e-3320-41d0-9feb-c4d3c158ba15)

**Comment by jona159** [comment]
UI: https://github.com/mint-o-badges/badgr-ui/pull/523
Server: https://github.com/mint-o-badges/badgr-server/pull/199
