### ISSUE TITLE
Bulk Award / CSV Spalten: Please adjust the copy

### ISSUE THREAD

**Issue by Annicelia** [mint-o-badges/badgr-ui#507]
Please adjust the copy to:

CSV-Spalten
Hier siehst du eine Vorschau der ersten 3 von 3 Zeilen deiner hochgeladenen Datei.
Wähle aus dem Dropdown-Menü die jeweils passende Spalten-Überschrift, damit die Daten beim Verschicken der Badges richtig zugeordnet werden können.

![Bildschirmfoto 2024-07-18 um 13 38 36](https://github.com/user-attachments/assets/f32a6d07-90e7-400b-aa4a-18dcfccbcc73)

**Comment by zven** [comment]
duplicat of https://github.com/mint-o-badges/badgr-ui/issues/486
