### ISSUE TITLE
ui | server: OAuth for meinbildungsraum

### ISSUE THREAD

**Issue by timber-they** [mint-o-badges/badgr-ui#51]
# What?
mint-o-badges is supposed to get connected to [meinBildungsraum](https://meinbildungsraum.de) (the national education platform). Therefore the login of meinBildungsraum is supposed to work for mint-o-badges as well. For that we want to connect via SSO/OpenID.

Serlo is also part of the national education platform and already has a connection via SSO/OpenID (see [github](https://github.com/serlo/documentation/wiki/SSO) and the [staging](https://de.serlo-staging.dev/auth/login)). The implementation code is on [github](https://github.com/search?q=org%3Aserlo%20mein%20Bildungsraum&type=code).

@mariopesch is currently trying to gather more information on that -> see bottom

# Open Questions
- How are users identified? Do they have an e-mail address?
    - Might be contained in the ID token
- Which version of OpenID is used? OpenID 1.0, OpenID 2.0, or OpenID Connect?
    - The link in [logout.tsx](https://github.com/serlo/frontend/blob/6bb7d770455ee107cdb7bf6b34300c2b1898f5ef/src/components/pages/auth/logout.tsx#L40) seems to indicate OpenID Connect (https://aai.demo.meinbildungsraum.de/realms/nbp-aai/protocol/openid-connect/logout)
    - Visiting https://aai.demo.meinbildungsraum.de it seems as if KeyCloak is used
    - According to the document, OpenID Connect is used
- How much of the authentication / authorization is done in meinbildungsraum? Or is meinbildungsraum only used as an alternative to password-based authentication?
    - It seems that meinBildungsraum mainly returns the ID token, thus replacing password-based authentication only
- Which authentication flow is configured in Keycloak? (Standard flow vs. implicit flow vs. OAuth 2.0 Device Authorization Grant)
- Where can we find more information, once new questions arise? Is there a documentation (of the interface, of the implementation, of the supposed way of using the interface)?
    - There is a document and we also have a contact whom we can ask stuff
- [Here](https://github.com/serlo/frontend/pull/1433/files) is the PR that introduced the SSO with Keycloak, it seems that an email for the user is returned. However i couldnt find the single-sign-on.tsx file in the current repo anymore, also didnt manage to find out when it was deleted, so this info could be outdated. 

# How
- Gather more information on SSO/OpenID
    - SSO (Single Sign On) is the general concept of only having to sign up on a single service (here meinBildungsraum)
    - OpenID is a protocol for using SSO in practice. It has three major versions, probably OpenID Connect (OIDC) is used here
    - OpenID Connect uses the OAuth 2.0 protocol. Since OAuth is an *authorization* protocol and OpenID Connect serves as an *authentication* method, this makes it a pseudo-authentication method
- Figure out how Serlo implemented it
- Figure out what steps are necessary to implement it in mint-o-badges
    - [Here](https://openid.net/certified-open-id-developer-tools/) is a list of certified implementations (including in python and TS). For python [this](https://github.com/IdentityPython/oidc-op) also mentions django, for TS only [this](https://github.com/damienbod/angular-auth-oidc-client) implementation seems to be certified which should work with Angular. However, all certified python implementations are public archives
    - It probably makes sense though to rather "add" it to the existing OAuth flow, than to implement it alongside it. Analysis is then needed, whether the currently used libraries also support OIDC
        - Probably we'll need additional libraries like `keycloak-angular` and `keycloak-js` to properly communicate with keycloak
- Write tests for SSO/OpenID
- Implement it
- Get tests running

## Stuff to figure out
- Figure out, how the authentication should work
    - It probably makes the most sense to get the ID token via the frontend, pass it back to the backend, validate the signature in the backend and pass an access token for the backend (as it is currently done) back to the frontend
    - The alternative would be to use the ID token from meinBildungsraum as authentication token for *our own* backend (thus verifying the signature in our backend every time). This seems more complicated though - at least if there's no library that does exactly that already
    - It seems that OAuth2 works by firstly authenticating to the backend and then giving an access token from the backend to the front end. Since we don't use meinBildungsraum for authorization, we only get the ID token from meinBildungsraum, which can't serve as an access token. Thus the first option seems to make more sense
- Figure out which OAuth2 flow to use
    - There's the *Implicit Grant Flow* and the *Authorization code grant flow*
    - If working with an access token (in addition to the ID token) the Authorization code grant flow seems to be more secure
    - We *probably* only need the ID token, since we only want to *authenticate* against meinBildungsraum, not *authorize* to get any additional user information
    - Thus the *Implicit Grant Flow* seems to be more appropriate - **if** it is indeed true that all the authorization etc. stays on our side and we use meinBildungsraum exclusively for authentication
- If we do indeed use the first option for authentication (validating the ID token in the backend and handing back an access token), we need to figure out how to validate the ID token in the backend
    - It seems as if [this](https://docs.authlib.org/en/latest/specs/oidc.html#module-authlib.oidc.core) function of authlib would achieve that
    - However, it seems a bit hacky since authlibs focus seems to lie on doing the whole OIDC authentication flow, not just validating the ID token. It's unclear, what the "normal" way of doing this would be

# Update
We now have an implementation guide PDF, sent in Mattermost and stored in our cloud.

# Status
We are waiting for credentials and other necessary data to start playing around with. Also, I'm waiting for a potential response from Serlo, giving some feedback on how I think it would make sense to implement it.

**Comment by timber-they** [comment]
We now have an account for meinBildungsraum, so I should be able to work on it next week

**Comment by timber-they** [comment]
It's possible that no major changes to the server are necessary at all, because the `django-oauth-toolkit` might already support it. It is important however that the client passes the [`Authorization code` grant](https://oauth.net/2/grant-types/authorization-code/). It might also make sense to add [PKCE](https://oauth.net/2/pkce/) for additional security. The main changes necessary however seem to be in the frontend to actually receive the key, to then pass it to the server.

**Comment by timber-they** [comment]
Sadly, still the client ID and secret seem to be missing (we currently only have credentials for a test user)

**Comment by timber-they** [comment]
It seems to make sense to use the [mozilla django OIDC library](https://mozilla-django-oidc.readthedocs.io/en/stable/installation.html) for the backend. We then need to make adjustments to the frontend to make calls to the relevant backend URLs that trigger the functionality of the API. This is different than I expected, because I seem to have misunderstood the working of the django-oauth-toolkit.

**Comment by timber-they** [comment]
Update:

    Add and configure mozilla-django-oidc
        
    The views that are provided by this library are not yet used. We need to
    expose them to the badgr-ui, make the relevant requests in the ui and
    probably create an interface in the UI that allows for adding an E-Mail
    address to the account that is authenticated via OIDC. For this also
    further configurations to the library have to be made, because currently
    it will try to automatically connect OIDC accounts to django users via
    the E-Mail address.

**Comment by timber-they** [comment]
Ok so we need three separate Client IDs / -Secrets and for each also a specific redirect uri; for the login this would be:
- https://api.openbadges.education/oidc/callback
- https://api.staging.openbadges.education/oidc/callback
- http://localhost:8000/oidc/callback

For the logout these *should* be the same uris.

**Comment by timber-they** [comment]
The OIDC functionality is now implemented and working for the backend; that means there currently exists a simple website (http://localhost:8000/oidcview/) in which you're either logged in and able to log out, or logged out and able to log in via OIDC from meinBildungsraum. As E-Mail a dummy E-Mail is stored, consisting of the OIDC subject identifier and `@unknown.unknown`; the user should then adjust this mail address.
However, firstly the log in via the frontend has to be implemented:
- [ ] The *Anmelden mit Mein Bildungsraum* Button makes a request to the backend
- [ ] The user validates if it's already logged in in the backend; if so, it returns an access token
- [ ] If not, it redirects the user to the meinBildungsraum login page
- [ ] Eventually the user gets redirected to our backend again. Since it should now be logged in, it returns an access token (with the same mechanism as in step 2)
- [ ] With the access token the user gets treated as logged in in the frontend

**Comment by timber-they** [comment]
Probably this is possible in an easier manner, using the functions of the existing libraries. The problem however currently is, that the access token is apparently stored in the session, but the client kind of expects a token to be stored in the browser session (is this a difference?).
I somehow need to convey to the OIDC authenticator (which comes from the oidc library!) to use the access token that the oidc library stored in some kind of session.
This should be possible, but since it's very poorly documented, actually doing it seems more difficult. But I guess this is the better way to proceed, since doing too much myself has security issues.

**Comment by timber-they** [comment]
Currently still open TODOs:
- [ ] Convert the session OIDC ID token to an access token for our backend
- [ ] Implement logout functionality
- [ ] Activate / implement PKCE

**Comment by timber-they** [comment]
I'm back to the drawing board with this one since I'm unsure if I'm on a useful track in implementing this. Here's the current options I see:

- Direct OIDC Authentication (*Session Authentication*): This would use the authentication mechanism from `mozilla-django-oidc`, essentially resulting in both *Token Authentication* and *Session Authentication* being allowed by our application
- Retrieve Access Token after OIDC Authentication (*Session Authentication -> Token Authentication*): After successful OIDC authentication this would make a special request to our authentication endpoint, which would then validate the valid authentication within the session (which `mozilla-django-oidc` took care of) and return an access token. So there would be only a single endpoint for which we utilize the *Session Authentication*, everything else would still use *Token Authentication*  exclusively. This is the approach I am currently following
- Use another backend library that hands out Access Tokens (*Token Authentication*): `mozilla-django-oidc` seems to (natively) only support authenticating the django user in the current session. Another django library *might* also support creating an Access Token that can then (somehow) be passed to the client directly (i.e. stored in the browser storage). It's unclear if such a library exists
- Retrieve OIDC Token on the client side and validate in the backend (*OIDC Authentication*): Additionally to normal access token authentication, we could also allow OIDC ID Tokens (or Access Tokens) as valid form of authentication against our backend. This way some Angular library would do the authentication against meinBildungsraum, receive the OIDC ID Token, store it in the browser storage and use it (instead of an Access Token handed out from the backend) to authenticate against the backend
- Retrieve OIDC Token on the client side and use it to request an access token from the backend (*OIDC Authentication -> Token Authentication*): After successful OIDC authentication the client would use its OIDC ID Token to make a special request to our authentication endpoint requesting a normal Access Token. The authentication endpoint would validate the received OIDC ID Token, which would be the only point for which we use the *OIDC Authentication* in the backend. This *might* comply with the OAuth standard of using a *Authorization Code* grant type

I will discuss with @mpfeil which option makes the most sense.

**Comment by timber-they** [comment]
The conversation with @mpfeil showed that option 2 might indeed still be the best option. I'll check if there's a library with which access token generation isn't so hacky as it currently seems to be with `oauth-provider` (which we currently use for password authentication).

**Comment by timber-they** [comment]
Except for the logout functionality this is fully implemented. However, it's unclear if this is desired: Should a click on "our" logout button trigger a logout from meinBildungsraum? (@zven)

**Comment by timber-they** [comment]
After some clarifications there are two TODOs left here:
- [ ] User logs out of OEB -> gets logged out of mbr
- [ ] User logs out of mbr -> gets logged out of OEB

**Comment by timber-they** [comment]
For the flow of the user logging out of mbr -> getting logged out of OEB, this is rather hard to test, since the request is done from the mbr server, which can't reach my `localhost`. So I'd first need to deploy this to staging. However, from the implementation there's also still one part missing: The validation of the logout token. Since I don't know yet what the logout token looks like (and it seems rather hard to find documentation on that online), I can't really do this before deploying it to Staging though.

This all seems rather hacky and I started thinking about whether it wouldn't be nicer to use the OIDC access token directly again. I also started implementing this already to try it out and spotted several (dis)advantages. **Advantages**:
- We use more default functions
- The whole thing is handled automatically by `mozilla-django-oidc`, the authorization works somewhat in a way as it was intended (at least by `mozilla-django-oidc`)
- The whole thing feels more like Single-Sign-On
- The logout mbr -> Logout OEB flow works automatically. That's because the authentication works in a way that we use the access token to make a request at mbr. If this works, the user is authenticated, if not then not. If the user logs out of mbr, the access token for mbr doesn't work anymore and the user is also logged out in our application

**Disadvantages**:
- We have no control over the expiry duration of the token. It currently seems to be set to 5 minutes
- `mozilla-django-oidc` doesn't automatically refresh the token
- `mozilla-django-oidc` has no implementation for refresh tokens (yet); the renewal of the access token would thus need to happen through a silent re-authentication at mbr (meaning that the browser (or an `iframe` in it) gets redirected to mbr and does the whole authentication again, except that it's silent, because the user is still logged in at mbr)
- We have no control over the scopes anymore. Until now access tokens are linked with scopes (e.g. `rw:Issuer`), that's not possible (natively) with OIDC tokens. On the other hand we also don't really use the scopes, since we never hand out access tokens with less scopes. OIDC access tokens simply have access to all scopes (that's something else than superuser status or similar)
- We'd basically have two systems for authentication. At least from the Django perspective, that's nothing unexpected though.


I'm going to talk to Sven about it tomorrow.

**Comment by timber-they** [comment]
So after talking to Sven we decided on a third option: Using a [angular-auth-oidc-client](https://github.com/damienbod/angular-auth-oidc-client) for obtaining and refreshing the access token and using `mozilla-django-oidc` to validate the access token in the backend against mbr and to create the user. This has the advantage that for login, refresh and logout we only use default functions in the way they were intended. Disadvantages are that we won't be able to use custom scopes for oidc users and that I'll need to work with yet another library.

**Comment by timber-they** [comment]
Open TODOs for this:

- [ ] Include and configure frontend library
- [ ] Figure out how to store the client ID / secret
- [ ] Configure backend library for new use case
- [ ] Disable not needed backend endpoints of backend library
- [ ] Remove not needed backend configuration changes made for the old implementation

**Comment by timber-they** [comment]
Well it's back and forth with this one. The problem with doing the authentication in the frontend is that there's no way of securely storing the client ID / secret in the client (or in the backend and *only* making it available to the client, since this would have to happen before authentication), since the code is executed on the client side - not on the server. Thus we ever need to employ a flow where no client secret is necessary (I'm unsure if mbr supports this) or we need to resort to a backend solution after all. Then there's still three options:
- Using `mozilla-django-oidc` and issue a normal access token, once the user authenticated. This has the disadvantages that we do the token creation ourselves, making it more likely that we fail, and also we still have to implement a secure logout mechanism. The worst that could happen here is that we fuck up so that unauthenticated users gain access
- Using `mozilla-djanog-oidc` to get the OIDC access token and use this. This has the disadvantages that we have to do some kind of silent token refresh in the background, since `mozilla-django-oidc` doesn't support refresh tokens. The worst that could happen here is that we fuck up the token refreshing, so that users get logged out on accident
- Using another backend library, that also supports refresh tokens. I don't know if this exists or if it would be well tested

**Comment by zven** [comment]
@timber-they I have a strong tendency to favor version 2. I'd rather logout some users by accident (in case our silent refresh mechanism fails) than screw up more security relevant mechanisms (see version 1).
In addition, I'd also prefer version 2 over version 3 since using a widely adopted library seems like the sensible choice when it comes to security relevant areas.

**Comment by timber-they** [comment]
So then there's the following TODOs left:
- [ ] Clean up implementation of using OIDC tokens
- [ ] Document that access token scope restrictions don't apply to OIDC logins
- [ ] Implement silent refresh of access token

**Comment by timber-they** [comment]
So it seems that due to the CSP settings of mbr the token renewal can't be done in an `iframe`. My proposal instead is to install a middleware in the server that checks if the OIDC access token expired and if so, redirects the user to the login page of mbr *if the user didn't log out* (I'm not entirely sure yet how to figure this out; maybe we can manage to use the `prompt=none` query parameter to receive an error if the user did indeed logout). Since this then happens in the main window (not in an `iframe`) we need to make sure that the user is redirected to the page they wanted to go to initially, and that also the session state isn't lost. Also we should try to remove the number of redirects for this silent token renewal.

Alternatives would be to convince mbr to change their CSP settings or try to utilize a refresh token after all...

**Comment by timber-they** [comment]
So the CSP problems seems to be solvable by setting the `prompt=none` parameter, which is possible albeit a *bit* hacky. Now there's the problem of third party cookies though: `mozilla-django-oidc` sets cookies for it's authentiation flow, which is blocked in the `iframe` because then they appear like third party cookies; those are blocked by most modern browsers.

**Comment by timber-they** [comment]
The third party cookies seem to be quite a problem. This is (for now) only a problem for browsers configured to block third party cookies, but I do assume that we also want to support those. As described e.g. [here](https://github.com/authts/oidc-client-ts/issues/1032) or [here](https://stackoverflow.com/a/54847567/7700150) this doesn't really seem to be solvable.

Also as suggested in the first post I thus suggest to resort to using refresh tokens after all. So right now we, once again, have a few options:
1. Use silent token renewal and redirect the whole browser to the "silent" token renewal (at least if third party cookies are blocked). We could try to make sure that the user is at least redirected to the page they came from afterwards
2. Use another backend library that supports refresh tokens (-> disadvantage: might be less tested and thus secure)
3. Manually expand `mozilla-django-oidc` to also support refresh tokens (as described in [this tutorial](https://dev.to/hesbon/customizing-mozilla-django-oidc-544p) (-> disadvantage: we might fuck something up and make the token refresh less secure)
4. Use our own access tokens after all (-> disadvantage: we'd still have to implement the single logout flow (securely) and might fuck something up both with the authentication and the logout, making both less secure)

I'm currently in favor of the third option. What do you think @zven?

**Comment by timber-they** [comment]
So there seems to be *yet another* option: Apparently `django-allauth` also [supports OIDC](https://docs.allauth.org/en/latest/socialaccount/introduction.html) as a relying party; they just call it "Social authentication". It might be possible to configure it in a way that it works with our setup, which would have the advantage that we don't need to use any extra library, since we already have `django-allauth` as a dependency.

**Comment by timber-they** [comment]
We decided against `django-allauth` and for the third option in the post before.

**Comment by timber-they** [comment]
Once more, TODOs for this are:
- [ ] Implement refresh token implementation from [here](https://dev.to/hesbon/customizing-mozilla-django-oidc-544p)
- [ ] Adjust implementation to work with our kind of token authentication (where the token is *not* stored in a django session)
- [ ] Cleanup / Refactor
- [ ] Test
