### ISSUE TITLE
accessibilit: Badge erstellen / KI tool

### ISSUE THREAD

**Issue by Annicelia** [mint-o-badges/badgr-ui#522]
for the copy at the beginning ("Wähle aus zwei Badge Kategorien..."), please use the OEB Black (#323232) instead of grey.
for the copy inside of the form fields, please use the dark grey (#6B6B6B) – right now, the letters are barely visible.

![Bildschirmfoto 2024-07-22 um 14 50 16](https://github.com/user-attachments/assets/878b6d86-0a45-4e47-a7c5-bb0da98d054b)
![Bildschirmfoto 2024-07-22 um 14 58 39](https://github.com/user-attachments/assets/2aa89440-d0bb-4a7f-9564-a821310ebd6d)
![Bildschirmfoto 2024-07-22 um 14 58 48](https://github.com/user-attachments/assets/068afbc9-82eb-4ec0-9cf5-f020d8084940)
![Bildschirmfoto 2024-07-22 um 14 59 01](https://github.com/user-attachments/assets/05b570af-5ba7-42b3-96a5-a5095770a004)

**Comment by Annicelia** [comment]
+ right now, when the user has used the button "Kompetenzen vorschlagen" within the KI-Badge-Assistent, the button is displayed green with white text in it. since green and white doesn't prove enough contrast to be distinguishable, please just make the copy blue again
![Bildschirmfoto 2024-07-22 um 15 04 08](https://github.com/user-attachments/assets/34193251-5adf-4370-b099-84d3c5f213b8)

**Comment by zven** [comment]
Updateing this would also entail redoing the ui with the new components. @YouQam might take over here.
