### ISSUE TITLE
ui: let users verify that they use the plattform for its intended use

### ISSUE THREAD

**Issue by zven** [mint-o-badges/badgr-ui#538]
Upon institution creation, users must confirm via checkbox, that they abide to the following rules. 

```
Hiermit bestätige ich, dass ich:
1.) ...berechtigt bin, für die genannte Institution einen Account anzulegen sowie Badges zu erstellen und zu vergeben.
2.) ...die Verantwortung für die Qualität der Kursangebote, der erstellten und vergebenen Badges sowie für die zugeordneten Kompetenzen trage.
3.) ...die Plattform nur für die vorgesehenen Zwecke nutze und jeglichen Missbrauch ablehne.
```

This confirmation must also be saved in the database.

**Comment by YouQam** [comment]
@jona159 which PR related to this ticket?

**Comment by zven** [comment]
@YouQam That got a bit chaotic with the whole newsletter and terms of service feature, see my comment here: https://github.com/mint-o-badges/badgr-server/issues/257#issuecomment-2500109463
