### ISSUE TITLE
issue badge: checkbox "Empfänger:in mit E-Mail benachrichtigen" selected by default

### ISSUE THREAD

**Issue by Annicelia** [mint-o-badges/badgr-ui#543]
I think I craeted this issue before but can't find it right now. Please make this checkbox when issuing the badge "Empfänger:in mit E-Mail benachrichtigen" selected by default.
![Bildschirmfoto 2024-07-29 um 10 00 08](https://github.com/user-attachments/assets/03f92707-4ad2-4ac4-9f47-45d2afbe6342)

**Comment by zven** [comment]
Ooooops, we already had that fixed here https://github.com/mint-o-badges/badgr-ui/issues/488 but seem to have broken it again
