### ISSUE TITLE
PDF certificate generates wrong output

### ISSUE THREAD

**Issue by schmidfranzi** [mint-o-badges/badgr-ui#566]
**Name the test case**
Generating the PDF certificate

**Describe the bug**
Feedback from a user: 
1. Auf den PDF-Zertifikaten wird als Name der Identifier ausgewiesen bei unseren aktuell zwei Badges, selbst wenn ein Empfänger*innen-Name eingegeben ist. Liegt wahrscheinlich an der Feldverknüpfung - hier wäre es super, wenn der Name, der im Empfänger*innen-Feld angezeigt würde, auch auftaucht. 
2. Der Infotext zum Badge und die Namen der Kompetenzen nach Esco werden im PDF abgekürzt. Wäre es hier möglich, dass alles komplett dargestellt wird? Ansonsten wäre eine Zeichenbegrenzung hilfreich, die das Darstellbare markiert - was bei den offiziellen ESCO-Namen aber ja auch nur begrenzt Sinn macht. 
3. Es wird eine S. 3 erzeugt, auf die nur ein Link rutscht, der auf S. 2 gehört - lässt sich dies technisch umstellen? 

**Screenshots**
[Badge Zertifikat.pdf](https://github.com/user-attachments/files/16437493/Badge.Zertifikat.pdf)

**Comment by jona159** [comment]
1. was fixed by #207
2. is its [own ticket](https://github.com/orgs/mint-o-badges/projects/2/views/1?pane=issue&itemId=73029094) now
3. is fixed with this PR
