### ISSUE TITLE
account confirmation mail: please update logo

### ISSUE THREAD

**Issue by Annicelia** [mint-o-badges/badgr-ui#580]
please replace this logo at the bottom in the gray area with the new one as well :)
![Bildschirmfoto 2024-08-06 um 13 38 48](https://github.com/user-attachments/assets/e5a2eb92-7463-4ac3-bf0f-91cd8b0e253a)

**Comment by YouQam** [comment]
It was resolved here https://github.com/mint-o-badges/badgr-ui/issues/501
