### ISSUE TITLE
not able to issue competency badge

### ISSUE THREAD

**Issue by Annicelia** [mint-o-badges/badgr-ui#581]
when trying to issue this competency badge, I get this error notification:
![Bildschirmfoto 2024-08-06 um 13 50 37](https://github.com/user-attachments/assets/88c671e8-a28b-4bbf-88e5-60912c363fb8)

**Comment by Annicelia** [comment]
... but the badge was issued as I can see on the badge detail page. even thow I go the error notification and was stuck on the issue badge page

**Comment by Annicelia** [comment]
... but I didn't get an email with the badge, so something here is not working

**Comment by jona159** [comment]
FIxed by [#214](https://github.com/mint-o-badges/badgr-server/pull/214)
