### ISSUE TITLE
welcome-page is missing?

### ISSUE THREAD

**Issue by Annicelia** [mint-o-badges/badgr-ui#607]
after confirming my account via email, the first page I should see is the new welcome-page ("Schön, dass du da bist"). I think at some point that worked, but yesterday a friend of mine created an account and he landed on "Meine Institutionen" right away instead of on "Schön, dass du da bist" at first.
https://www.figma.com/design/rq5IOcBWjVAl7tmvtq0GqS/Use-Cases?node-id=2887-5888&t=lmK4VCAvuNMYCDWn-4
![Bildschirmfoto 2024-08-13 um 11 42 15](https://github.com/user-attachments/assets/78c30c59-2dd8-48ea-bb60-fde5304a7f6e)

**Comment by zven** [comment]
@Annicelia Did this also happen when you tested on the 26.08.2024 yourself? And has your friend maybe already been added to an institution before actually signing up?

**Comment by Annicelia** [comment]
@zven when I tested the last time and today, it was there, so maybe it was just a hiccup or so ;)

**Comment by zven** [comment]
Great! We'll close it, then.
