### ISSUE TITLE
ui: add beta information

### ISSUE THREAD

**Issue by jona159** [mint-o-badges/badgr-ui#609]

**Comment by Annicelia** [comment]
@jona159 please add the beta information like displayed in the screenshots and adjust the style of footer. "Betaphase" will link to the corresponding section in the FAQ as soon as it is added (we will let you know once the FAQ are revised).
 ![Bildschirmfoto 2024-09-23 um 09 55 28](https://github.com/user-attachments/assets/3c9d3e26-1f52-41e6-863a-e73bd3adc655)
![Bildschirmfoto 2024-09-23 um 09 43 47](https://github.com/user-attachments/assets/647f6ac0-c5d6-46e9-b6f5-e009333ca218)
![Bildschirmfoto 2024-09-23 um 09 50 11](https://github.com/user-attachments/assets/8de748a4-75ce-45cc-b858-0099c73b9514)
![B-Wheel](https://github.com/user-attachments/assets/90dacedd-2f6d-43be-8986-87776bb758ec)
https://www.figma.com/design/rq5IOcBWjVAl7tmvtq0GqS/Use-Cases?node-id=7692-18441&t=hkllsXOldWJifVzF-4

**Comment by Annicelia** [comment]
please note: the design of the footer has changed in the meantime 
![Bildschirmfoto 2024-10-08 um 11 01 19](https://github.com/user-attachments/assets/03769aaa-c045-493f-b112-0c46bf004ed3)

**Comment by zven** [comment]
Note:
* some of those elements are already created in the learning path branch -> copy those
* "Betaphase" does not link to the FAQs yet since they are not yet updated.

**Comment by zven** [comment]
will be implemented onc #564 is done

**Comment by zven** [comment]
Already coverd by #746 and #564?
- Welcome page still missing.
