### ISSUE TITLE
Mail zur Aktivierung des OEB-Accounts kommt nicht an

### ISSUE THREAD

**Issue by HannnahPue** [mint-o-badges/badgr-ui#612]
**Name the test case**
Account Aktivierungs-Mail kommt nicht an

**Describe the bug**
Nach Registrierung auf der OEB Plattform bekommt unsere Kollegin Marion Sonnenberg die Mails zur Aktivierung des Accounts nicht (sonnenberg@matrix.ggmbh.de)

**To Reproduce**
Registrierung als User auf der Plattform

**Expected behavior**

**Screenshots**

**Desktop (please complete the following information; remove if not applicable):**

-   OS: [e.g. Windows 10, MacOS 14.03, Ubuntu]
-   Browser [e.g. chrome, safari]
-   Version [e.g. 22]

**Smartphone (please complete the following information; remove if not applicable):**

-   Device: [e.g. iPhone6]
-   OS: [e.g. iOS8.1]
-   Browser [e.g. stock browser, safari]
-   Version [e.g. 22]

**Additional context**
Add any other context about your observations here.

**Comment by zven** [comment]
Apparently, the account confirmation mail came a week later. I'm currently investigating the exact chain of events.

**Comment by zven** [comment]
The only information I got here was that sending the email from our system was never triggered (based on logs on email server). However, we could not reproduce this issue.
