### ISSUE TITLE
typos/formatting/link QR Code vergeben

### ISSUE THREAD

**Issue by Annicelia** [mint-o-badges/badgr-ui#624]
Please adjust the highlighted areas according to the wireframe. Notice that there is a word missing as well at 4. (Badge-Detail-Seite). This word should link to the actual Badge detail badge, not to "Meine Institutionen"
![Bildschirmfoto 2024-08-19 um 10 19 41](https://github.com/user-attachments/assets/2dd62af4-f11e-419a-b99f-a21474f2442f)

**Comment by zven** [comment]
Unfortunately, there is still a number of things that are not looking as in the designs:

![Image](https://github.com/user-attachments/assets/be8e5fc9-5e1a-4c60-8f17-5875260b9afa)
