### ISSUE TITLE
create badge – use own visual

### ISSUE THREAD

**Issue by Annicelia** [mint-o-badges/badgr-ui#627]
when uploading an own visual when creating a badge, you have to to it twice. the first time it never works
![Bildschirmfoto 2024-08-19 um 11 34 07](https://github.com/user-attachments/assets/5e424030-ae0b-4a4f-8a10-a15e4e1f011f)

**Comment by timber-they** [comment]
This is not only related but the same

**Comment by zven** [comment]
@YouQam On Safari, I can't reproduce the issue neither on `staging` nor on our production environment.

**Comment by zven** [comment]
@Annicelia Does the problem still occur? Which browser have you been using? Have you tried clearing the browse cache and removed old website data?

**Comment by Annicelia** [comment]
@YouQam yes it still occours in Firefox, although I just cleared the cache

**Comment by YouQam** [comment]
> [@YouQam](https://github.com/YouQam) yes it still occours in Firefox, although I just cleared the cache

Thank you for the feedback. It'll be resolved here #480

**Comment by zven** [comment]
duplicate of #480
