### ISSUE TITLE
editing badge image: error notification

### ISSUE THREAD

**Issue by Annicelia** [mint-o-badges/badgr-ui#628]
when editing an existing badge and uploading an own visual, there is this error notification and the badge moves to the left frame ("Unseren Editor nutzen"). so it is not possible to edit the image (https://openbadges.education/public/badges/DJtgXqcpSF-jK86_eECtdA)

![image (2)](https://github.com/user-attachments/assets/618e4997-b8ae-4c55-9dc5-3d9218d87d99)

**Comment by timber-they** [comment]
I think this is the same as #480

**Comment by timber-they** [comment]
The error message seems to indicate that an image was uploaded that is too large. However, I also can't upload an own visual on editing a badge with a framed visual, so this does seem to be an issue.

**Comment by timber-they** [comment]
I'm gonna work on this together with #480, since both affect the image upload

**Comment by zven** [comment]
@YouQam Since you are currently working on #480: Are you aware of the changes made by @timber-they here?

**Comment by YouQam** [comment]
> @YouQam Since you are currently working on #480: Are you aware of the changes made by @timber-they here?

Yes. I'm working on the branch they created.
