### ISSUE TITLE
ui | server: adjust qr code download

### ISSUE THREAD

**Issue by jona159** [mint-o-badges/badgr-ui#644]
Instead of downloading just the qr code, it should download something similar to the pdf: 
![qrcode_download](https://github.com/user-attachments/assets/0aba58e4-7ae0-4cd6-a4e5-9e54156f257d)

**Comment by jona159** [comment]
@Annicelia could you export the arrow as an image (jpg or png)  for us?

**Comment by jona159** [comment]
@Annicelia would it be possible to get this arrow as an image (png or jpg) ?

**Comment by Annicelia** [comment]
@jona159 sure :) here you go 
![pfeil-qr-code-plakat](https://github.com/user-attachments/assets/161cd6fb-e736-440a-840d-6eb90536e7f7)

**Comment by jona159** [comment]
ui: https://github.com/mint-o-badges/badgr-ui/pull/674/ 
server: https://github.com/mint-o-badges/badgr-server/pull/233/

**Comment by jona159** [comment]
@Annicelia this is what the qrcode download would currently look like: 

![Image](https://github.com/user-attachments/assets/f353a08a-0d79-476a-8596-12e5eae3d851)

I didnt manage to overlap the badge image on the qr code yet, it is a bit complicated Do you think it is fine like this? Let me know if i should make some visual adjustments

**Comment by jona159** [comment]
server: https://github.com/mint-o-badges/badgr-server/pull/233
ui: https://github.com/mint-o-badges/badgr-ui/pull/674
