### ISSUE TITLE
ui: handle long issuer names

### ISSUE THREAD

**Issue by jona159** [mint-o-badges/badgr-ui#649]
Very long issuer names destroy the layout of PDF and the issuer detail page, e.g: 
![long_issuer](https://github.com/user-attachments/assets/6e84f75b-4299-486c-8b89-d870d3690276)

**Comment by zven** [comment]
@Annicelia suggested to limit institution names to 90 characters.

@jona159 Would a character limit (and maybe some UI adjustments) solve the issues we currently have with longer institution names?
