### ISSUE TITLE
ui: add plus icon to institution card for creating a new badge

### ISSUE THREAD

**Issue by zven** [mint-o-badges/badgr-ui#651]
Based on the discussion [here](https://github.com/mint-o-badges/badgr-ui/issues/585) we'll adjust the institution card for two cases:

No badges yet:
* two buttons: "Neuen Badge erstellen" and "Lernpfad erstellen"

Badges already created:
* row of images of already created badges with a "+" button at the leftmost position that functions as the "Badge erstellen" button
* two buttons: "Badge vergeben" and "Lernpfad erstellen"

**Comment by zven** [comment]
@Annicelia Could you cook up some designs for this? Similar to those you linked here: https://github.com/mint-o-badges/badgr-ui/issues/585#issuecomment-2296504177

**Comment by umut0** [comment]
![image](https://github.com/user-attachments/assets/876f7090-b22f-477f-8187-01cc112ac896)
Like this maybe?

**Comment by Annicelia** [comment]
@umut0 yes! I love it! (just "Badges vergeben" with s for more than one Badge in the first button :)

**Comment by Annicelia** [comment]
@umut0 however, i would put the plus button at the beginning. otherwise, if an institution has a lot of badges, it will be very far back or at the bottom and may not catch the eye

**Comment by Annicelia** [comment]
@zven https://www.figma.com/design/rq5IOcBWjVAl7tmvtq0GqS/Use-Cases?node-id=7651-10700&t=na1Ba2iI2BWa80Y5-4
![Image](https://github.com/user-attachments/assets/f5f53b2a-341b-4e58-8b22-9fc06453c4b8)

**Comment by zven** [comment]
duplicate of #564

**Comment by zven** [comment]
> [@zven](https://github.com/zven) https://www.figma.com/design/rq5IOcBWjVAl7tmvtq0GqS/Use-Cases?node-id=7651-10700&t=na1Ba2iI2BWa80Y5-4 ![Image](https://github.com/user-attachments/assets/f5f53b2a-341b-4e58-8b22-9fc06453c4b8)

@umut0 Have you seen the designs that @Annicelia has provided above? Would it make sense to do this as an extra task and stick with your updated institution card from #564 for now?

**Comment by Annicelia** [comment]
Hi, I just changed the colour of the plus button and the "Badge vergeben" Button: 
![Bildschirmfoto 2024-10-29 um 19 36 01](https://github.com/user-attachments/assets/bbb2e431-7cb8-4928-b7ec-bf232d32fde6)

**Comment by zven** [comment]
@umut0 Institution cards are currently simplyfied. Hence, I'll put this issue back into `Backlog`

**Comment by Annicelia** [comment]
@umut0 
![Bildschirmfoto 2024-11-25 um 14 32 45](https://github.com/user-attachments/assets/785d08b4-1e54-4e9a-aabf-c301ef565e79)
![Bildschirmfoto 2024-11-25 um 14 32 18](https://github.com/user-attachments/assets/eed90a1c-fec0-415a-aa85-02b90da71070)
https://www.figma.com/design/rq5IOcBWjVAl7tmvtq0GqS/Use-Cases?node-id=10165-17542&t=MvPV90mpl1qr0ViV-4

**Comment by Annicelia** [comment]
@umut0 let me know in case you have any questions regarding the cards
