### ISSUE TITLE
mobile: burger menu is cut off

### ISSUE THREAD

**Issue by Annicelia** [mint-o-badges/badgr-ui#659]
![Signup - Open Educational Badges](https://github.com/user-attachments/assets/53b93582-7091-410b-8e47-55fe6012e1c2)

**Comment by zven** [comment]
It seems to be related to the initial (?) zoom level. Tested on an iPhone SE 2020 with a rather smallish screen by modern standards:

Loading the website initially:
![IMG_6038](https://github.com/user-attachments/assets/2810afef-522a-4504-b0bf-66d0aa80ea20)

Whole page screenshot mode (does not look broken):
![IMG_6037](https://github.com/user-attachments/assets/d0ae70f5-f144-4c07-8b0b-cb66aff945fa)

After pinching the website to zoom out (looks fine):
![IMG_6042](https://github.com/user-attachments/assets/1c2067f6-1be0-46e9-afb3-c6796af893ff)

**Comment by YouQam** [comment]
@Annicelia Can you please specify which mobile device/OS you used?

**Comment by zven** [comment]
@YouQam You can easily reproduce the issue if you use the developer tools of your browser and set a fake mobile screen size of 430 x 480 (e.g. on Firefox: Tools -> Browser Tools -> Web Developer Tools -> Responsive Design Mode).

**Comment by zven** [comment]
iPhone SE (2nd Edition): 375 px wide
