### ISSUE TITLE
ui: adjust layouts to match long issuer names

### ISSUE THREAD

**Issue by jona159** [mint-o-badges/badgr-ui#665]

**Comment by YouQam** [comment]
@jona159 Can you add more details?

**Comment by jona159** [comment]
@YouQam sure, we have some issuers on production with long names. On the issuer detail page, the layout is a bit broken as a result, e.g. here: ![Image](https://github.com/user-attachments/assets/26e32940-ccc6-40a4-871e-7db3e9f6ffb4)

We should adjust it, so that the buttons remain in their original size and the issuer logo should not be distorted etc.

**Comment by Annicelia** [comment]
@jona159 this doesn't seem to be fixed?
 ![Image](https://github.com/user-attachments/assets/24a1d1ea-a7dd-4a24-84b0-fd2d19817273)
