### ISSUE TITLE
ui: cancelling badge award does not work

### ISSUE THREAD

**Issue by jona159** [mint-o-badges/badgr-ui#668]
The badge is still awarded if i try to cancel after clicking on "Badge vergeben"

Edit: same if one tries to cancel the creation of a badge

**Comment by jona159** [comment]
@zven Turns out this could become a bit more complicated than i thought. Currently the ```Cancel``` buttons just routes the user back to a different page. If we want to allow the user to cancel the creation / award of a badge after the submit button was already clicked it would require some changes in different places. Though it is doable, i dont know if we want to spend some hours on this issue (as it was not a requested feature yet i think). Alternative suggestion would be to disable the ```Cancel``` button just like the ```Submit``` button after the user has clicked submit, which is just 1 LoC.

**Comment by zven** [comment]
Just disable the `Cancel` button once we award the badge.
