### ISSUE TITLE
ui: error message on big image upload

### ISSUE THREAD

**Issue by timber-they** [mint-o-badges/badgr-ui#673]
When uploading a custom image for the badge that is bigger than our maximum size, a cryptic error message is displayed (see [this ticket](https://github.com/orgs/mint-o-badges/projects/2/views/1?pane=issue&itemId=75285514)).

**Comment by zven** [comment]
@jona159 also add information about the max. file size to allowed formats

**Comment by YouQam** [comment]
This issue occurs due to the limited size of `MEMCACHED_MAX_ITEM_SIZE` which is by default 1 MB. Although there is a possibility to increase it, but it’s not recommended see [[here](https://hub.docker.com/r/bitnami/memcached)](https://hub.docker.com/r/bitnami/memcached).

To DO:
    - [x]  prevent large custom-images `(above 250 KB)` from being loaded
    - [x]  add info about the max. file size
