### ISSUE TITLE
KI-Tool: Händisch Kompetenzen hinzufügen

### ISSUE THREAD

**Issue by Annicelia** [mint-o-badges/badgr-ui#688]
right now, on staging it looks like this once the arrow opened the section:
![Bildschirmfoto 2024-09-09 um 10 40 57](https://github.com/user-attachments/assets/aa1a25c7-74c8-47dc-b956-d9e231196ef6)

can you make it look more like the initial wireframe, so that the form fields shows once the arrow is unfolded?
<img width="753" alt="Bildschirmfoto 2024-09-09 um 10 44 47" src="https://github.com/user-attachments/assets/db96c3a0-7967-42f4-8a43-c3d0abd5a70e">

**Comment by jona159** [comment]
Note: This happens when trying to edit a competency-badge that has no competencies yet
