### ISSUE TITLE
Bulk Award CSV Upload

### ISSUE THREAD

**Issue by Annicelia** [mint-o-badges/badgr-ui#691]
After uploading the CSV file for bulk awarding a badge, both of the dropdowns have 4 options. Can't we limit them to "E-Mail" and "Name" (and delete "N/A" and "Nachweis URL" ?
![Bildschirmfoto 2024-09-09 um 12 05 36](https://github.com/user-attachments/assets/2bd093eb-064f-4380-97f5-49cc2f3f0916)

**Comment by zven** [comment]
@Annicelia Removing "Nachweis URL" would make sense, "N/A" is there for the case, that there might be additional columns in the file that do not contain any information that is name or emai address.

**Comment by Annicelia** [comment]
ok :)

**Comment by zven** [comment]
Todo:

- [ ] remove `Nachweis URL` from UI
