### ISSUE TITLE
ui | server: pdf preview is slow / odd on Safari

### ISSUE THREAD

**Issue by zven** [mint-o-badges/badgr-ui#701]
Private badge detail page in my backpack (on Safari): 

First attempt to open PDF preview for badge A (no preview, but badge can be downloaded):
![Image](https://github.com/user-attachments/assets/ef9804f5-e4ed-4ef6-be92-a8e49e64fece)

Second attempt for badge A (after closing the preview window and opening it again via PDF-download button):
![Image](https://github.com/user-attachments/assets/0d15baf4-ad89-4a4f-8c0f-821aeb9fdfe7)

First attempt to open PDF preview for badge B shows preview for badge A:
![Image](https://github.com/user-attachments/assets/bef6429d-4ba5-425c-9adb-07b131309311)

Second attempt for badge B (after closing the preview window and opening it again via PDF-download button) shows badge B:
![Image](https://github.com/user-attachments/assets/7d02253a-e3dd-4913-a83d-e2e9c07b3a91)

Note:
On Firefox, this seems to work. 🤔

**Comment by YouQam** [comment]
The issue here was related to async function with safari. I also noticed that with all types of browsers the previous pdf view was shown before showing selected and correct pdf preview. Both issues were resolved.
