### ISSUE TITLE
cc license information badges

### ISSUE THREAD

**Issue by Annicelia** [mint-o-badges/badgr-ui#712]
i created two screens for adding the cc license information on badges:
a) badge detail page
b) badge editor, right before button "create badge"
![Bildschirmfoto 2024-09-19 um 17 16 37](https://github.com/user-attachments/assets/da645d60-d169-46a6-bd11-6c7f9b02ee14)
![Bildschirmfoto 2024-09-19 um 17 06 40](https://github.com/user-attachments/assets/810699e1-9d60-4692-8f73-8f3a26809dee)

**Comment by Annicelia** [comment]
@jona159 sorry can you please add two changes: the link in both cases should be to https://creativecommons.org/publicdomain/zero/1.0/

und lease use![Image](https://github.com/user-attachments/assets/51877543-84bb-4ee8-a03a-612470e13f82)
![Image](https://github.com/user-attachments/assets/789ae1bc-b4eb-4720-a98e-8781ad9eafb7)
 this image instead of the two icons

**Comment by zven** [comment]
@jona159 This is not supposed to be used until we have the whole  terms of service and newsletter feature implemented. Is that purely a UI element that is not yet shown? Or do we simply show it for every badge?
