### ISSUE TITLE
badges overview / badge request: add button

### ISSUE THREAD

**Issue by Annicelia** [mint-o-badges/badgr-ui#717]
can this green button be displayed as soon as there are open badge requests via a qr code allocation, so that the institutions can see the requests quickly? (it would link to the badge detail page)
![Bildschirmfoto 2024-09-24 um 16 23 17](https://github.com/user-attachments/assets/8e6bcc05-f0bd-4130-aeaa-df35b21fa13e)

**Comment by jona159** [comment]
ui: https://github.com/mint-o-badges/badgr-ui/pull/719
server: https://github.com/mint-o-badges/badgr-server/pull/244
