### ISSUE TITLE
institution erstellen: title style of form fields

### ISSUE THREAD

**Issue by Annicelia** [mint-o-badges/badgr-ui#723]
can you please style the title "Logo-Bild" in the same way as the rest of the titles (Name der Institution) etc, it looks greyish and maybe not as bold as the rest?
![Bildschirmfoto 2024-09-26 um 13 54 40](https://github.com/user-attachments/assets/017ca975-0061-42f5-bd39-bfa85317ea99)

**Comment by timber-they** [comment]
@jona159 can you link the PR pleas?
