### ISSUE TITLE
institution erstellen: make adress fields mandatory

### ISSUE THREAD

**Issue by Annicelia** [mint-o-badges/badgr-ui#724]
please make the adress fields mandatory as well so that the institutions have to enter all details

**Comment by Annicelia** [comment]
@jona159 I just created an institution on staging without entering the adress and didn't receive an error notification ("Wir lieben Donnerstage")

**Comment by jona159** [comment]
@Annicelia the changes were not yet on the staging system, we had to restart it. Now you should receive an error
