### ISSUE TITLE
ui: integrate terms of service and newsletter into system

### ISSUE THREAD

**Issue by zven** [mint-o-badges/badgr-ui#746]
The newsletter signup form is shown in two different views and three different cases:

First time user:
* brevo newsletter form is integrated into the registration form (https://www.figma.com/design/rq5IOcBWjVAl7tmvtq0GqS/Use-Cases?node-id=5622-6801&t=xjLoAdF6JxojJUNQ-4) @jona159 already experimented with said form a bit. Please contact @zven in case you need that form
* users have to agree to terms of service via checkbox (terms of service page linked)
* the page highlighting the successfull registration is adjusted to include information about the double opt in newsletter mail: https://www.figma.com/design/rq5IOcBWjVAl7tmvtq0GqS/Use-Cases?node-id=5622-6849&t=xjLoAdF6JxojJUNQ-4

Users who already have an account:
* after logging in, they see a page where must confirm the terms of service: https://www.figma.com/design/rq5IOcBWjVAl7tmvtq0GqS/Use-Cases?node-id=5622-7027&t=xjLoAdF6JxojJUNQ-4
* users have to agree to terms of service via checkbox (terms of service page linked)
* terms of service page is similarly styled like imprint and privacy policy page
* until the users have accepted the new terms of service -> account is marked as "not verified" (and thus, institutions and badges are hidden from the catalogue views) until at least one owner of an institution has accepted the terms of service
* if users have accepted the terms of service, they are forwarded to the newsletter page (see below, pre-filled with their information from their accounts)

Users simply want to sign up to the newsletter:
* newsletter page: https://www.figma.com/design/rq5IOcBWjVAl7tmvtq0GqS/Use-Cases?node-id=8410-27998&t=OZWXbW6PBoTXXNb3-4
* accessible via footer: https://www.figma.com/design/rq5IOcBWjVAl7tmvtq0GqS/Use-Cases?node-id=8451-37596&t=OZWXbW6PBoTXXNb3-4
* in case the user is already logged in, the fields are pre-filled

Users that have not accepted the new terms:
* simplyfied version as in figma designs

**Comment by zven** [comment]
Designs for terms of service workflow are now finalzed: https://www.figma.com/design/rq5IOcBWjVAl7tmvtq0GqS/Use-Cases?node-id=5622-2808&t=xnF7ADVRIS11kZPD-4

**Comment by zven** [comment]
@jona159 I'll post the actual text for the terms of service page tomorrow. It's ready, though I still need to clean it up and export it as a txt

**Comment by jona159** [comment]
@Annicelia could you export this image for me please ? :) ![Image](https://github.com/user-attachments/assets/88d0084f-2596-4972-bdcb-0764f2131497)

**Comment by zven** [comment]
@YouQam Did you move this ticket back to `Next` since you were missing the PR?
It looks like everything regarding the newsletter and terms of service that is UI-related is here https://github.com/mint-o-badges/badgr-ui/pull/715
and server-related is here: https://github.com/mint-o-badges/badgr-server/pull/273

The `[WIP]` in the UI PR seems to be an oversight. According to my information @jona159  is done with the feature.
