### ISSUE TITLE
Add Duration to the Badge detail card

### ISSUE THREAD

**Issue by jona159** [mint-o-badges/badgr-ui#750]
![Image](https://github.com/user-attachments/assets/84c97e5e-2b46-40a6-b066-660ac1ea712e)

Duration should be under Kategorie according to designs,

**Comment by jona159** [comment]
There is a server PR as well: https://github.com/mint-o-badges/badgr-server/pull/258

**Comment by Annicelia** [comment]
@YouQam I don't see the duration of the badge I just created on staging? 
![Image](https://github.com/user-attachments/assets/954460c2-7bd4-4574-a2b6-1b2a062872c7)

**Comment by YouQam** [comment]
> @YouQam I don't see the duration of the badge I just created on staging? ![Image](https://private-user-images.githubusercontent.com/164371483/375291289-954460c2-7bd4-4574-a2b6-1b2a062872c7.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3Mjg1NDk5NjMsIm5iZiI6MTcyODU0OTY2MywicGF0aCI6Ii8xNjQzNzE0ODMvMzc1MjkxMjg5LTk1NDQ2MGMyLTdiZDQtNDU3NC1hMmI2LTFiMmEwNjI4NzJjNy5wbmc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjQxMDEwJTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI0MTAxMFQwODQxMDNaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT04NTFmOWQyNDE4ZWY2Mjc0ZDExNjY2MzBiODlhM2RjMDJiODRhODA4ZTEwZGNjMTQ5Y2U3MjQ1NDQ2YTk1MGIwJlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCJ9.-WvfnUYNBTW_XXR2a6KfvgVyLkEDuf1tMt0ADYSVgU0)

@Annicelia I'll have a look into it.

**Comment by YouQam** [comment]
@Annicelia try it again, now it should work.
