### ISSUE TITLE
edit institution menu: confusing icons

### ISSUE THREAD

**Issue by Annicelia** [mint-o-badges/badgr-ui#753]
Could you please change this people-icon for "Bearbeiten" to the same icon used in the edit qr code menu (the pen)

![Bildschirmfoto 2024-10-10 um 09 49 16](https://github.com/user-attachments/assets/a4a2f0b3-531d-4c68-9627-4b126f02bc52)

![Bildschirmfoto 2024-10-10 um 10 02 26](https://github.com/user-attachments/assets/c9d7fe16-c008-4f56-a5b4-4b3a04e0dd71)

**Comment by zven** [comment]
fixed
