### ISSUE TITLE
standardize time display in competencies

### ISSUE THREAD

**Issue by Annicelia** [mint-o-badges/badgr-ui#755]
after a certain number of minutes, the duration is displayed in hours. can't we then always display the duration in hours? 
![Bildschirmfoto 2024-10-10 um 10 44 47](https://github.com/user-attachments/assets/6bb3fbf3-96e1-48cd-ad0f-178febee0ced)

**Comment by zven** [comment]
@Annicelia If we want to do that, we need to decide how we want to round "odd" durations: What are 20 minutes? 0.5 h? 0.3 h? Or 17 minutes? Is there any best practice how to do such things?

At the moment: Until 120 we show minutes. After that, we show full hours and cut off the remaining minutes. E.g. 130 min. -> 2 h

**Comment by zven** [comment]
duplicate of https://github.com/mint-o-badges/badgr-ui/issues/770
