### ISSUE TITLE
update issuer / institution catalog page

### ISSUE THREAD

**Issue by zven** [mint-o-badges/badgr-ui#764]
The institution catalog page is still extremely outdated. It looks like this, atm:

![Image](https://github.com/user-attachments/assets/32423ecd-ad31-4ed0-b5d1-76810fcec05d)

The new design and layout for institution cards can be found here: https://www.figma.com/design/rq5IOcBWjVAl7tmvtq0GqS/Use-Cases?node-id=5081-40392&t=wbCt817bkmRF9IWN-4

Screenshot for reference:
![Image](https://github.com/user-attachments/assets/485999dd-1200-4d25-8a0b-4bcdb1d72193)

**Comment by zven** [comment]
@Annicelia As already discussed via chat: Shall we include the green bar from the `Institutionen A-Z`-page also for `Lernpfade A-Z` and `Badges A-Z`?

**Comment by Thiemann96** [comment]
first draft in #811, help appreciated for some small ui problem

**Comment by zven** [comment]
@Thiemann96 Although I'm not @Annicelia, mobile version looks good to me :-) 👍

**Comment by Annicelia** [comment]
@Thiemann96 , thanks, can you adjust the dropdown so that it has the same height as the search field as provided in the wireframes above (desktop + mobile) ? 
and the space between the copy and the tag "Schule" seems to be a bit large on iPad
