### ISSUE TITLE
ui: display hours instead of minutes

### ISSUE THREAD

**Issue by zven** [mint-o-badges/badgr-ui#770]
At the moment, users can enter minutes when creating badges. 

Up to a certain duration, we are showing minutes (120 min.), after that hours with 0.5 steps (always rounding up). We should do this in a consistent way and are currently discussing two options:

1. We always show minutes and hours in combination e.g. `1 h 12 min`, `13 h` or `59 min`. We would also provide separate hour and minute fields for the duration information of badges / competencies.

2. As already implemented in the [learning path feature](https://github.com/mint-o-badges/badgr-ui/issues/564) we could also display the duration information in the format `HH:MM Stunden` or `HH:MM h`. The duration input fields for badges and competencies would need to be adjusted to only accept this format (and highlight that in a smart way).

Update time display / entry information in the following places:

- [x] badge cards
- [x] badge views
- [x] competencies (website and PDF)
- [x] badge editing and creation process

**Comment by zven** [comment]
After talking to @Annicelia: We go with version 2. `HH:MM h`

**Comment by umut0** [comment]
There is an hourPipe in the learningPath PR that converts times into this fomat.

**Comment by umut0** [comment]
![image](https://github.com/user-attachments/assets/5d901887-a2de-4820-a071-684f3083a801)
We leave this field as it is? or also the h representation?

**Comment by Annicelia** [comment]
can you round up or down here so that there is always a full number of hours without minutes? then I would leave it like it is, "82 Stunden". and please make it "Lernzeit" instead of "Lernzeiten"

**Comment by zven** [comment]
Extra todo:
Limit input form to max `999:59 h`

**Comment by umut0** [comment]
The pdf will be fixed in #716

**Comment by umut0** [comment]
Fixed display for competencies which was still broken

**Comment by zven** [comment]
@umut0 The time input for competencies as part of the badge creation process is still open, right?

![Image](https://github.com/user-attachments/assets/b6692006-323e-4ec0-8d4b-c4ecb90d04fb)
