### ISSUE TITLE
ui: adjust menu structure and update footer

### ISSUE THREAD

**Issue by zven** [mint-o-badges/badgr-ui#78]
Details can be found here: https://app.asana.com/0/1205782519509072/1206713453273409

**Comment by zven** [comment]
@YouQam and @umut0 mycelia suggested to adjust the menu structure (see link in card description). Having our somewhat inflexible css framework in mind: Do you think that's a quick win (half a day or less) or something bigger?

**Comment by YouQam** [comment]
I think half a day should be enough, I can work on it after this card [update about us page](https://github.com/orgs/mint-o-badges/projects/2/views/1?pane=issue&itemId=54123977)

**Comment by YouQam** [comment]
Since not all pages are completely translated, I'll comment out language implementation.
