### ISSUE TITLE
ui: order of elements in lists and tables

### ISSUE THREAD

**Issue by zven** [mint-o-badges/badgr-ui#796]
Currently things are ordered differently or randomly. We should specify how we order things in lists/tables etc... and make it consistent.

**Comment by zven** [comment]
@Annicelia Input would be appreciated here ;-)

**Comment by Annicelia** [comment]
badges and institutions 
- on the overview pages: alphabetically
- on ‘my institutions’: alphabetically

wallet/backpack:
display of badges: chronological (newest first)
display of competences: by learning time (i.e. the competence with the highest time unit is at the top)

did I miss something?

**Comment by Annicelia** [comment]
;) jup. and in the rucksack newest first like the badges

**Comment by Annicelia** [comment]
yes. what would the other dropdown options be in this case?

**Comment by Thiemann96** [comment]
Alphabetically, ascending or descending. We could also add "Date of creation" or something like that for issuers (just like with badges for instance)

**Comment by Thiemann96** [comment]
waiting for performance update to the page, right now sorting takes too long
