### ISSUE TITLE
ui: update imprint page

### ISSUE THREAD

**Issue by zven** [mint-o-badges/badgr-ui#798]
We need to update our imprint page (again!) ;-)

Text can be found here:

[Impressum OEB.odt](https://github.com/user-attachments/files/17620569/Impressum.OEB.odt)

For styling, please use the existing style in the imprint page.

**Comment by zven** [comment]
@YouQam PR for this issue seems to be open still. Moved to `Done` by accident?

**Comment by YouQam** [comment]
@zven No, it's not done yet. Don't know how it ends up in done section.
