### ISSUE TITLE
ui: once badge is awarded or QR code for badge request is added, no editing possible anymore

### ISSUE THREAD

**Issue by zven** [mint-o-badges/badgr-ui#806]
Badges should only be editable as long as they have not been awarded and no QR code for requesting badges has been generated. When one of the two cases apply, the "edit badge" button should be greyed out.

When the user has created a badge and wants to award it for the first time, the following dialogue should appear and warn the user: https://www.figma.com/design/rq5IOcBWjVAl7tmvtq0GqS/Use-Cases?node-id=8522-29761&t=BN76ohmrrN1YJ9H0-4

![Image](https://github.com/user-attachments/assets/b23b511d-a98e-4d80-a64c-5c9d7fdb7536)

The same applies for the QR code feature: https://www.figma.com/design/rq5IOcBWjVAl7tmvtq0GqS/Use-Cases?node-id=8522-29738&t=BN76ohmrrN1YJ9H0-4

![Image](https://github.com/user-attachments/assets/d3ee56ad-d4da-4417-8fff-9c1f35e4062f)

Please note that the button `Badge vergeben` does not make sense in the second case and should be replaced with `QR Code erstellen`.

**Comment by umut0** [comment]
Do we do the same for learningpaths?

**Comment by zven** [comment]
@umut0 Good thought! For _adding_ badges to a learning path, no: Since a learning path creator is also able to add external badges to their learning path, this way you could block editing of external badges.

Nevertheless, it would make sense to add this mechanism before _awarding_ the final learning path badge.
