### ISSUE TITLE
ui: fix minutes error message style on badge creation

### ISSUE THREAD

**Issue by jona159** [mint-o-badges/badgr-ui#815]
After entering an invalid number, the error message style is broken
![Image](https://github.com/user-attachments/assets/cf6dd44a-b4d0-485a-bf57-38b5c5341257)

**Comment by jona159** [comment]
@Thiemann96 I think originally this ticket was just intended to fix the problem that the error message would break the layout of the input fields (meaning that the input fields are not aligned horizontally anymore when an error appears). But i agree that we should also prevent strings here. Would you prefer to open a new ticket for the original issue or do you think you can also fix the input layouts in case of an error on this card?

**Comment by zven** [comment]
In addition, I was also informed that there seems to be an issue with "jumping" of the number and hour input field.

**Comment by zven** [comment]
@Thiemann96 Maybe this is a related issue? https://github.com/mint-o-badges/badgr-ui/issues/850

**Comment by Thiemann96** [comment]
> @Thiemann96 I think originally this ticket was just intended to fix the problem that the error message would break the layout of the input fields (meaning that the input fields are not aligned horizontally anymore when an error appears). But i agree that we should also prevent strings here. Would you prefer to open a new ticket for the original issue or do you think you can also fix the input layouts in case of an error on this card?
> 
> btw there currently seem to be commits from the other PR in this one


I will fix the error in this card as well !

**Comment by Thiemann96** [comment]
<img width="964" alt="grafik" src="https://github.com/user-attachments/assets/4fe3a870-6363-45f7-a17e-ac442c828724">

**Comment by Thiemann96** [comment]
@jona159 i moved this pr to a new one due to several conflicts with the upstream branch
