### ISSUE TITLE
Dauer neu hinzugefügter Kompetenzen 

### ISSUE THREAD

**Issue by HannnahPue** [mint-o-badges/badgr-ui#875]
Dauer neu hinzugefügter Kompetenzen Paste the test case here.

**Describe the bug**
Bei neu hinzugefügten Kompetenzen kann ich die Dauer eintragen, z.B. 4 Stunden. Sobald ich aber auf Kompetenz hinzufügen klicke, springt die Dauer immer zurück auf eine Stunde (siehe Screenshots). Beim Erstellen des Badges ist die Zeitangabe dann wieder korrekt, so wie ich sie eingetragen habe.

**To Reproduce**

**Expected behavior**

**Screenshots**

**Desktop (please complete the following information; remove if not applicable):**

-   OS: [e.g. Windows 10, MacOS 14.03, Ubuntu]
-   Browser [e.g. chrome, safari]
-   Version [e.g. 22]

**Smartphone (please complete the following information; remove if not applicable):**

-   Device: [e.g. iPhone6]
-   OS: [e.g. iOS8.1]
-   Browser [e.g. stock browser, safari]
-   Version [e.g. 22]
<img width="1268" alt="Bildschirmfoto 2024-11-25 um 08 18 30" src="https://github.com/user-attachments/assets/6c0fe959-5ff1-4a99-bee8-bb81a6291ca7">
<img width="1244" alt="Bildschirmfoto 2024-11-25 um 08 18 22" src="https://github.com/user-attachments/assets/4262421d-d4c4-4ebf-adcc-e3c1823f91a0">

**Additional context**
Add any other context about your observations here.

**Comment by zven** [comment]
duplicate of https://github.com/mint-o-badges/badgr-ui/issues/850
