### ISSUE TITLE
error notification pdf certificate

### ISSUE THREAD

**Issue by Annicelia** [mint-o-badges/badgr-ui#910]
I am unable to see the pdf certificate:
![Bildschirmfoto 2024-12-12 um 16 18 45](https://github.com/user-attachments/assets/afde3ed7-b309-4a63-9b85-4c69d8b661be)
{
  "headers": {
    "normalizedNames": {},
    "lazyUpdate": null
  },
  "status": 500,
  "statusText": "OK",
  "url": "https://api.staging.openbadges.education/v1/earner/badges/pdf/WrP_wF4tQrSSolssvWCXRw",
  "ok": false,
  "name": "HttpErrorResponse",
  "message": "Http failure response for https://api.staging.openbadges.education/v1/earner/badges/pdf/WrP_wF4tQrSSolssvWCXRw: 500 OK",
  "error": {}
}

**Comment by jona159** [comment]
Should be fixed by #914, please reopen if it still exists
