### ISSUE TITLE
please make the footer look even more like the wireframe

### ISSUE THREAD

**Issue by Annicelia** [mint-o-badges/badgr-ui#918]
i just couldn't find the git hub card for the footer, so here's the screenshot of the wireframe again:
<img width="761" alt="Bildschirmfoto 2024-12-16 um 09 08 22" src="https://github.com/user-attachments/assets/52c3c109-df1f-42aa-b143-a07d08783fe5" />
every link, including the company names and “betaphase”, should have the same blue as the mail address and be underlined to indicate that it is a link. and please give it a little more space so that it has a large green space at the top and bottom like in the wireframe. what is new: since there are 4 words now on the right because "Nutzungsbedingungen" is new, I adjusted the spacing and only FAQ is bold now. please adjust this spacing as well. here is the link to the design again if you want to look at the spacing: 
https://www.figma.com/design/rq5IOcBWjVAl7tmvtq0GqS/Use-Cases?node-id=10780-10428&t=wHPNzNSvOKGOhy8i-4

**Comment by Annicelia** [comment]
this is how it looks right now on staging: 
![Bildschirmfoto 2024-12-16 um 09 15 32](https://github.com/user-attachments/assets/9bd3f430-4f5c-43a0-806a-55acde7ee559)

**Comment by jona159** [comment]
@Annicelia regarding the color of the links, i am not 100% sure but i think they should be blue by default but change to purple once they were visited by you. I think it would be good to have such a visual indication for the user to see which links he/she previously visited, what do you think? 
Also, can you tell me where the "Betaphase" link should point to?

**Comment by Annicelia** [comment]
ok when it has the blue by default it is fine, but can you underline the link-words any way? :)
"Betaphase" should point to the Betaphase-section in the new FAQ, but since this is not yet available (it will be part of the CMS in a few weeks) you can remove the link from the word for now :)

**Comment by jona159** [comment]
@Annicelia i made the adjustments and also made the Beta-Logo a bit bigger, could you check if this works for you? https://deploy-preview-928--openeducationalbadges.netlify.app/

**Comment by Annicelia** [comment]
great, thank you @jona159 ! just one thing: can you make sure that the lower text block does not run so far over to the right? preferably only as far as the upper one :)
![Bildschirmfoto 2024-12-17 um 14 22 02](https://github.com/user-attachments/assets/930a5e70-10a2-44d4-97fc-8432aea39ac1)
