### ISSUE TITLE
ui: competency visualization in badge view

### ISSUE THREAD

**Issue by zven** [mint-o-badges/badgr-ui#93]
re-style badge view (design follows)

Further issues:
* participation badge contains section "Competencies"

**Comment by zven** [comment]
Comparison of current state and wireframes:

![Image](https://github.com/mint-o-badges/badgr-ui/assets/2930332/cd3d5b2e-88e4-4d1f-840c-526ffb43ae90)

As a first step, we only adjust the "competency boxes":
- use the bright purple / white design
- display name and duration on the box itself
- when you open "Details ansehen", the box folds out and you get to see
  - description
  - category

**Comment by jona159** [comment]
Done as part of #247

**Comment by zven** [comment]
Done with #247
